### ISSUE TITLE
json_extract_path with nested query

### ISSUE THREAD

**Issue by lsusatyo-gcmlp** [r-dbi/RPostgres#105]
Hi,

I don't think the nested json_extract_path function is working.

Here's the scenario:

CREATE TABLE Meal (
    id INT
  , recipe JSONB
);

INSERT INTO Meal (id, recipe)
VALUES (
1,
'{
  "meal": [{
  "calories" : 900,
  "serves" : [{"min": 2, "max": 4}],
  "fruit" : [{"id": 1, "qty": 2}, {"id": 4, "qty": 3}],
  "veggie" : [{"id": 4, "qty": 1}, {"id": 2, "qty": 10}]
 }]
}');

In this example: to get meal with calorie of 900, one can do this:

SELECT recipe FROM meal where json_extract_path(recipe, 'recipe', 'calories') = 900 

I tried with both with 900 or '900', none succeed. Please advise. Thank you!

**Comment by krlmlr** [comment]
Maybe you can try something like

```sql
SELECT id, json_extract_path(recipe, 'recipe', 'calories') FROM meal
```

to see the actual values?
