### ISSUE TITLE
trouble using certificates and keys to connect

### ISSUE THREAD

**Issue by koseri** [r-dbi/RPostgres#106]
We don't allow password authentication to our postgres database, and use certificates and keys instead. I have something that works just fine when I use RPostgreSQL, but does not work with RPostgres:

`this_works <- dbConnect ( RPostgreSQL::PostgreSQL(), 
host =  "111.22.33.44", user = "pm", 
dbname = "dbname = thedb sslcert=pm.crt sslkey=pm.key")`

Although, honestly, it's a bit awkward with the whole `dbname = "dbname = thedb..."` 

However, I cannot find any permutation that works with **RPostgres**. These all fail, complaining about not being able to find pg_hba.conf entries:

```
this_fails <- dbConnect ( RPostgres::Postgres(), host =  "111.22.33.44", user = "pm", dbname = "thedb sslcert=pm.crt sslkey=pm.key")
Error in eval(substitute(expr), envir, enclos) : 
FATAL:  no pg_hba.conf entry for host "123.45.67.89", user "pm", database "fnma_edna sslcert=pm.crt sslkey=pm.key", SSL on
FATAL:  pg_hba.conf rejects connection for host "123.45.67.89", user "pm", database "fnma_edna sslcert=pm.crt sslkey=pm.key", SSL off
```

This also fails
```
this_also_fails <- dbConnect ( RPostgres::Postgres(), host =  "111.22.33.44", user = "pm", dbname = "dbname = thedb sslcert=pm.crt sslkey=pm.key")
Error in eval(substitute(expr), envir, enclos) : 
  FATAL:  no pg_hba.conf entry for host "123.45.67.89", user "pm", database "dbname = fnma_edna sslcert=pm.crt sslkey=pm.key", SSL on
FATAL:  pg_hba.conf rejects connection for host "123.45.67.89", user "pm", database "dbname = fnma_edna sslcert=pm.crt sslkey=pm.key", SSL off
```

Do we really need a separate pg_hba.conf setting for RPostgres? That strikes me as unlikely, but I will readily admit to ignorance on the matter.

**Comment by krlmlr** [comment]
Can you try:

```r
please_try <- dbConnect(
  RPostgres::Postgres(),
  host = "111.22.33.44",
  user = "pm",
  dbname = "thedb",
  sslcert = "pm.crt",
  sslkey = "pm.key"
)
```

RPostgres doesn't support the notation `dbname = 'dbname=[] sslmode=...'`, because we call [`PQconnectdbParams()`](https://www.postgresql.org/docs/9.6/static/libpq-connect.html) with `expand_dbname = false`. You need to pass all arguments separately to `dbConnect()`.
