### ISSUE TITLE
/bin/gtar: not found (Ubuntu 14.04)

### ISSUE THREAD

**Issue by mconigliaro** [r-dbi/RPostgres#110]
I get `/bin/gtar: not found` when running `devtools::install_git("git://github.com/rstats-db/RPostgres")` on Ubuntu 14.04. There's no such thing as `gtar`. Here's the fix:

     ln -s /bin/tar /bin/gtar

**Comment by krlmlr** [comment]
Thanks. The preferred method is one of

```r
remotes::install_github("r-dbi/RPostgres")
devtools::install_github("r-dbi/RPostgres")
```

but I'm not sure if this fixes the `gtar` error.

**Comment by Finesim97** [comment]
Sorry for posting on an old issue, but if you don't have root: 
``` R
Sys.setenv(TAR = "/bin/tar")
``` 
or run in your shell:
``` sh
export TAR="/bin/tar"
```
Have a nice day.
