### ISSUE TITLE
dbWriteTable docs misrepresent field.types parameter

### ISSUE THREAD

**Issue by ilyaminati** [r-dbi/RPostgres#113]
I just lost time writing code based on `dbWriteTable` documentation. The docs say that `dbWriteTable` uses the `field.types` parameter, but it actually does not. Whatever the issues may be regarding using or not using the patch in #45 , there is no reason for the docs to be misleading. (Related: #104)

**Comment by krlmlr** [comment]
The docs are probably for `DBI::dbWriteTable()`, which describes what the backends *should* implement, but perhaps not what is actually implemented. Can you please try the development version? I have merged #45.
