### ISSUE TITLE
SSL connection to AWS instance

### ISSUE THREAD

**Issue by johnreichert** [r-dbi/RPostgres#115]
I have an AWS hosted PostgreSQL database where I have forced SSL connections with the database setting rds.force_ssl = 1.  When connecting to my database with RPostgres from a machine where I had not installed the AWS public postgres key (available from AWS in an S3 bucket), I was able to establish a connection.  That seemed odd to me - does RPostgres somehow include the AWS public keys in its build?

**Comment by mmuurr** [comment]
Did you reboot your RDS instance after switching to "force SSL" mode?
In many cases, that's required to actually switch on the SSL option (described here:
 [http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_PostgreSQL.html#PostgreSQL.Concepts.General.SSL]).

**Comment by krlmlr** [comment]
I'm not aware of any keys included with RPostgres, maybe with the client library? Did rebooting help?
