### ISSUE TITLE
Client connection drops when using pgbouncer

### ISSUE THREAD

**Issue by richfitz** [r-dbi/RPostgres#116]
I am trying to RPostgres with [pgbouncer](https://pgbouncer.github.io/) for connection pooling.  When used this way I can issue only one command using `RPostgres` before something that it sends causes `pgbouncer` to drop the connection.  This does not happen when connecting with `psql` or `RPostgreSQL`

The set-up to replicate this issue is a bit involved but docker helps

Start a postgres docker container setting a password to `foo`

```
docker run --rm --name postgres -e "POSTGRES_PASSWORD=foo" -p 5432:5432 postgres
```

Start a second container with `pgbouncer` acting as a per-transaction connection pooler (the same thing occurs with per-statement pooling, but using `pool_mode=session` works just fine it seems)

```
docker run --rm --name pgbouncer --link postgres:postgres -e "POSTGRES_ENV_PASSWORD=foo" -e "pool_mode=transaction" -p 6432:6432 kafka/pgbouncer
```

Then verify that things work:

```
psql -h localhost -p 6432 -U postgres -c \\dt
```

(enter password `foo` - it should print `No relations found`)

Then, from R:

```r
con <- DBI::dbConnect(RPostgres::Postgres(),
                      host = "localhost", port = 6432,
                      user = "postgres", password = "foo",
                      dbname = "postgres")
DBI::dbListTables(con)
# character(0)
DBI::dbListTables(con)
# Error:
DBI::dbListTables(con)
# message type 0x5a arrived from server while idle
# message type 0x74 arrived from server while idle
# message type 0x54 arrived from server while idle
# message type 0x5a arrived from server while idle
# Error: 
```

(you may have to pause for a second to get the messages)

In both error messages there is nothing missing - it just says "Error:"

The traceback is:

```
14: stop(list(message = "", call = NULL, cppstack = NULL))
13: .Call("RPostgres_result_create", PACKAGE = "RPostgres", con, 
        sql)
12: result_create(conn@ptr, statement)
11: initialize(value, ...)
10: initialize(value, ...)
9: new("PqResult", ptr = result_create(conn@ptr, statement), sql = statement)
8: .local(conn, statement, ...)
7: dbSendQuery(conn, statement, ...)
6: dbSendQuery(conn, statement, ...)
5: dbGetQuery(conn, paste0("SELECT tablename FROM pg_tables WHERE schemaname !='information_schema'", 
       " AND schemaname !='pg_catalog'"))
4: dbGetQuery(conn, paste0("SELECT tablename FROM pg_tables WHERE schemaname !='information_schema'", 
       " AND schemaname !='pg_catalog'"))
3: .local(conn, ...)
2: DBI::dbListTables(con)
1: DBI::dbListTables(con)
```

On the pgbouncer logs, I see:

```
2017-02-23 13:18:31.728 11 LOG C-0x1f99df0: postgres/postgres@172.17.42.1:42635 login attempt: db=postgres user=postgres tls=no
2017-02-23 13:18:31.730 11 LOG C-0x1f99f78: (nodb)/(nouser)@172.17.42.1:42637 closing because: cancel request for idle client (age=0)
2017-02-23 13:18:31.731 11 LOG C-0x1f99f78: (nodb)/(nouser)@172.17.42.1:42639 closing because: cancel request for idle client (age=0)
2017-02-23 13:18:31.734 11 WARNING C-0x1f99df0: postgres/postgres@172.17.42.1:42635 FIXME: query end, but query_start == 0
2017-02-23 13:18:31.735 11 LOG C-0x1f99f78: (nodb)/(nouser)@172.17.42.1:42641 closing because: cancel request for idle client (age=0)
```

The first line is issued after the connection is made (login attempt)
The second is issued after the first `dbListTables` command (closing because: cancel request for idle client)
The third is after the second `dbListTables` command
Lines 4-5 come after the third `dbListTables` command

With `RPostgreSQL`

```
con <- DBI::dbConnect(RPostgreSQL::PostgreSQL(),
                      host = "localhost", port = 6432,
                      user = "postgres", password = "foo",
                      dbname = "postgres")
DBI::dbListTables(con)
# character(0)
DBI::dbListTables(con)
# character(0)
DBI::dbListTables(con)
# character(0)
```

with logs listing only

```
2017-02-23 13:21:26.470 11 LOG C-0x1f99f78: postgres/postgres@172.17.42.1:42669 login attempt: db=postgres user=postgres tls=no
```

clean up containers
```
docker rm -f pgbouncer postgres
```

**Comment by krlmlr** [comment]
Thanks for the writeup. I have no idea where to even start debugging this. Maybe we're issuing commands that are incompatible with transaction pooling (https://pgbouncer.github.io/features.html)?

**Comment by richfitz** [comment]
I get the feeling this is more a protocol issue than a command issue - `dbListTables` is just doing a `SELECT` query isn't it?

**Comment by krlmlr** [comment]
Yes, I was thinking about queries that happen during `dbConnect()`.

**Comment by richfitz** [comment]
Ah, sorry. I honestly find the whole S4 thing so baffling I really struggle to how any of the DBI driver packages are wired up (not your fault, of course)

**Comment by krlmlr** [comment]
This is not about S4. We do set the client encoding to UTF-8, for instance, in the C++ code -- maybe pgbouncer is confused by this?

**Comment by krlmlr** [comment]
We should make connections more reliable. Bookmarking this issue, closing for now.
