### ISSUE TITLE
Implement pgCancel

### ISSUE THREAD

**Issue by chochkov** [r-dbi/RPostgres#117]
libpq supports PgCancel to allow the client to request the cancelation of queries - https://www.postgresql.org/docs/9.6/static/libpq-cancel.html. I'd like it if interrupts (`Ctr+C`) during long-running queries got captured in R and a PgCancel could be propagated through libpq.

That is, I would expect the `Ctr+C` below to stop the query, but it doesn't:

```
> dbGetQuery(con, 'select pg_sleep(5)')
^C
^C

```

**Comment by krlmlr** [comment]
Related: https://github.com/r-dbi/DBI/issues/69.

**Comment by krlmlr** [comment]
Solved by #193, thanks @zozlak!
