### ISSUE TITLE
Can't write tables with row names

### ISSUE THREAD

**Issue by kalyaniram88** [r-dbi/RPostgres#120]
I ran this to create a table in my schema 
dbWriteTable(con,"mtcars", mtcars[1:5, ],append=TRUE)
and got this
Error in connection_copy_data(conn@ptr, sql, value) : 
  Failed to initialise COPY

**Comment by r2evans** [comment]
When the data.frame has no row names, it works.

```r
x <- mtcars[1:5,]
dbWriteTable(con, "mtcars", x, append = TRUE)
# Error in connection_copy_data(conn@ptr, sql, value) (from insert.R#97) : 
#   Failed to initialise COPY
rownames(x) <- NULL
dbWriteTable(con, "mtcars", x, append = TRUE)
# [1] TRUE
```

(This isn't a fix, it's a workaround.)

**Comment by krlmlr** [comment]
`dbWriteTable()` now has `row.names = FALSE` as default. I'll be working on fixing all other cases.

**Comment by krlmlr** [comment]
Looks like all relevant tests pass. Please file a new issue if problems persist.
