### ISSUE TITLE
SSL Connection failing

### ISSUE THREAD

**Issue by elbamos** [r-dbi/RPostgres#122]
I'm unable to get an ssl connection even when forcing it in the command:

```
 con <- dbConnect(RPostgres::Postgres(),dbname = 'dbname=[] sslmode=prefer', 
+                  host = '[]', 
+                  port = 5432, 
+                  user = '[]',
+                  password = '[]')
Error in connection_create(names(opts), as.vector(opts)) : 
  FATAL:  no pg_hba.conf entry for host "[]", user "[]", database "dbname=[] sslmode=prefer", SSL off
```

Is there something I'm not doing?  (This feels like a compilation issue to me, is there any indication of whether `RPostgres` compiled properly with SSL?)

**Comment by boxuancui** [comment]
I have similar issues with SSL connection. When I try to establish SSL connection to either Redshift or Postgres instance, I get the following error:

	con <- dbConnect(
		RPostgres::Postgres(),
		host = "redshift_host_name",
		port = 5439,
		user = "XXX",
		password = "XXX",
		dbname = "XXX",
		sslmode = "verify-ca",
		sslcert = "some_ssl_cert_dir",
		sslrootcert = "some_ssl_cert_dir")
	)
    
    > Error in connection_create(names(opts), as.vector(opts)) : 
        certificate present, but not private key file "/Users/bcui/.postgresql/postgresql.key"

Traceback shows:

	7:stop(
		list(
			message = "certificate present, but not private key file \"/Users/bcui/.postgresql/postgresql.key\"\n",
			call = connection_create(names(opts), as.vector(opts)),
			cppstack = list(
				file = "",
				line = -1L,
				stack = c(
					"1   RPostgres.so                        0x000000010aec4809 _ZN4Rcpp9exceptionC2EPKcb + 185",
					"2   RPostgres.so                        0x000000010aec4690 _ZN4Rcpp4stopERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEE + 48",
					"3   RPostgres.so                        0x000000010aeca4f2 _ZN12PqConnectionC2ENSt3__16vectorINS0_12basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEENS5_IS7_EEEES9_ + 482",
					"4   RPostgres.so                        0x000000010aec90ff _Z17connection_createNSt3__16vectorINS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEENS4_IS6_EEEES8_ + 95",
					"5   RPostgres.so                        0x000000010aebf4c8 _RPostgres_connection_create + 168",
					"6   libR.dylib                          0x000000010101e007 do_dotcall + 327",
					"7   libR.dylib                          0x000000010104b70c Rf_eval + 988",
					"8   libR.dylib                          0x00000001010a5683 do_begin + 451",
					"9   libR.dylib                          0x000000010104b93e Rf_eval + 1550",
					"10  libR.dylib                          0x00000001010a23a7 Rf_applyClosure + 1543",
					"11  libR.dylib                          0x000000010104b847 Rf_eval + 1303",
					"12  libR.dylib                          0x00000001010a61f2 do_set + 1858",
					"13  libR.dylib                          0x000000010104b93e Rf_eval + 1550",
					"14  libR.dylib                          0x00000001010a5683 do_begin + 451",
					"15  libR.dylib                          0x000000010104b93e Rf_eval + 1550",
					"16  libR.dylib                          0x000000010104b93e Rf_eval + 1550",
					"17  libR.dylib                          0x00000001010a5683 do_begin + 451",
					"18  libR.dylib                          0x000000010104b93e Rf_eval + 1550",
					"19  libR.dylib                          0x00000001010a23a7 Rf_applyClosure + 1543",
					"20  libR.dylib                          0x000000010104b847 Rf_eval + 1303",
					"21  libR.dylib                          0x00000001010a5683 do_begin + 451",
					"22  libR.dylib                          0x000000010104b93e Rf_eval + 1550",
					"23  libR.dylib                          0x00000001010a3877 R_execClosure + 919",
					"24  libR.dylib                          0x00000001010a3475 R_execMethod + 613",
					"25  methods.so                          0x00000001016ce274 R_dispatchGeneric + 2388",
					"26  libR.dylib                          0x00000001010e86ba do_standardGeneric + 634",
					"27  libR.dylib                          0x000000010104b9b8 Rf_eval + 1672",
					"28  libR.dylib                          0x00000001010a61f2 do_set + 1858",
					"29  libR.dylib                          0x000000010104b93e Rf_eval + 1550",
					"30  libR.dylib                          0x00000001010a5683 do_begin + 451",
					"31  libR.dylib                          0x000000010104b93e Rf_eval + 1550",
					"32  libR.dylib                          0x00000001010a23a7 Rf_applyClosure + 1543",
					"33  libR.dylib                          0x000000010104b847 Rf_eval + 1303",
					"34  libR.dylib                          0x00000001010a61f2 do_set + 1858",
					"35  libR.dylib                          0x000000010104b93e Rf_eval + 1550",
					"36  libR.dylib                          0x00000001010a5683 do_begin + 451",
					"37  libR.dylib                          0x000000010104b93e Rf_eval + 1550",
					"38  libR.dylib                          0x00000001010a23a7 Rf_applyClosure + 1543",
					"39  libR.dylib                          0x000000010104b847 Rf_eval + 1303",
					"40  libR.dylib                          0x00000001010d6333 Rf_ReplIteration + 675",
					"41  libR.dylib                          0x00000001010d7945 R_ReplConsole + 149",
					"42  libR.dylib                          0x00000001010d7872 run_Rmainloop + 82",
					"43  rsession                            0x0000000100749c59 _ZN7rstudio1r7session12runEmbeddedRERKNS_4core8FilePathES5_bb7SA_TYPERKNS1_9CallbacksEPNS1_17InternalCallbacksE + 425",
					"44  rsession                            0x0000000100729a59 _ZN7rstudio1r7session3runERKNS1_8ROptionsERKNS1_10RCallbacksE + 3161",
					"45  rsession                            0x000000010003e828 main + 24168",
					"46  rsession                            0x0000000100003434 start + 52",
					"47  ???                                 0x0000000000000009 0x0 + 9"
				)
			)
		)
	)
	6:.Call(`_RPostgres_connection_create`, keys, values)
	5:connection_create(names(opts), as.vector(opts))
	4:.local(drv, ...)
	3:dbConnect(
		RPostgres::Postgres(),
		host = "redshift_host_name",
		port = 5439,
		user = "XXX",
		password = "XXX",
		dbname = "XXX",
		sslmode = "verify-ca",
		sslcert = "some_ssl_cert_dir",
		sslrootcert = "some_ssl_cert_dir"
	)

When I revert back to v0.1-4, it works fine. Something changed for v0.1-5?

**Comment by krlmlr** [comment]
@boxuancui: v0.1-5 is very recent, it looks like you're experiencing a different problem. Would you mind opening a new issue? A bisect would help a lot, too.

**Comment by boxuancui** [comment]
@krlmlr Sorry I figured out my mistake, thus I deleted my comment. I used wrong SSL parameter in the connection object.

**Comment by krlmlr** [comment]
Thanks. Cleaning up.

**Comment by boxuancui** [comment]
@elbamos Now I think about it, my problem might be helpful for you. Have you tried interacting with the SSL parameters directly?

	con <- dbConnect(
		RPostgres::Postgres(),
		host = "[]",
		port = 5432,
		user = "[]",
		password = "[]",
		dbname = "[]",
		sslmode = "verify-ca",
		sslfactory = "",
		sslrootcert = "your_ssl_cert_directory"
	)

You can find the full list of SSL parameters here: https://www.postgresql.org/docs/9.6/static/libpq-ssl.html. Especially look at Table 32-1 and Table 32-2.

**Comment by paolontra** [comment]
for some reason, SSL stopped working for us as well. I have forked the repository and reverted the commits from august and it works again: https://github.com/paolontra/RPostgres

dbConnect(RPostgres::Postgres(),dbname = "zzzz",
          host = "yyyy", port = 5432,
          user = "xxxxx", password = "", sslmode="required", .sslmode="required")

This is the issue I was getting: Error in connection create(names(opts), as.vector(opts)) : object '_RPostgres_connection_create' not found connection

I am now using this repo to enable SSL: devtools::install_github("paolontra/RPostgres",force=TRUE,ref="pao")

**Comment by krlmlr** [comment]
The notation suggested by @elbamos, `dbname = 'dbname=[] sslmode=prefer', doesn't work because we call [`PQconnectdbParams()`](https://www.postgresql.org/docs/9.6/static/libpq-connect.html) with `expand_dbname = false`. You need to pass all arguments separately to `dbConnect()`.

@paolontra: The `object '_RPostgres_connection_create' not found` seems unrelated. Could you please test reinstalling the current develipment version of RPostgres?

**Comment by GiovaniBasile** [comment]
Helped me to find the parameters
https://www.postgresql.org/docs/9.6/libpq-connect.html#LIBPQ-PARAMKEYWORDS
