### ISSUE TITLE
RPostgres and dplyr's summarise/tally function causes error for SQL's COUNT function

### ISSUE THREAD

**Issue by burkovae** [r-dbi/RPostgres#131]
I encountered the follwing strange behaviour. I'm not really sure whether it is a problem of `RPostgres` or error in `dplyr`.

```
con <- DBI::dbConnect(drv = RPostgres::Postgres(), [connection strings])
dplyr::tbl(con, 'sometable') %>%
	dplyr::summarise(n = n())	
```
```
Error in result_create(conn@ptr, statement) : 
  ERROR:  count(*) must be used to call a parameterless aggregate function LINE 1: SELECT COUNT() AS "n"
```

and the same for 

```
dplyr::tbl(con, 'sometable') %>%
	dplyr::tally(n = n())
```

On the other hand, this works:

```
con <- DBI::dbConnect(drv = odbc::odbc(), [connection strings])
dplyr::tbl(con, 'sometable') %>%
	dplyr::summarise(n = n())
# works!
```

If you think this bug is related to some other project, please tell me so I can post this issue elsewhere. Thanks!

**Comment by krlmlr** [comment]
Thanks. This seems to be a dbplyr problem, the issue tracker is at https://github.com/tidyverse/dplyr/issues. I wonder which server version of PostgreSQL are you using? Can you please share the output of `... %>% dbplyr::sql_render()` ?
