### ISSUE TITLE
foreign tables are not recognised

### ISSUE THREAD

**Issue by richfitz** [r-dbi/RPostgres#134]
If a database has a foreign table (e.g. created with `CREATE FOREIGN TABLE`), then when one writes to it directly with `DBI::dbWriteTable(..., append = TRUE)`, the driver does not recognise that the table exists and tries to create it first, which then fails with

    ERROR:  relation "burden_estimate_stochastic" already exists

This is pretty hard to set up a minimal example because it requires two working copies of postgres.  I can send a docker compose script that sets things up if that would be useful for testing.

**Comment by richfitz** [comment]
Which means the much simpler trigger is that foreign tables are not recognised by `DBI::dbExistsTable` , which means `dbListTables` (which queries the `pg_tables`) is the culprit.  That is probably fixable with information here: http://pgsql.bugs.narkive.com/fEYCfa1p/bugs-bug-6478-foreign-tables-not-displayed

**Comment by richfitz** [comment]
The fix in

https://github.com/r-dbi/RPostgres/pull/29

will fix this issue it appears (I _knew_ I'd seen a similar thing somewhere here).  Is it possible to merge than in before https://github.com/r-dbi/DBI/issues/24 is resolved?

**Comment by krlmlr** [comment]
Can you use `dbWriteTable(overwrite = TRUE)`? Table enumeration is unstable in MariaDB as well, at some point I removed calls to `dbExistsTable()` from `dbWriteTable()` there -- we can do the same here.

**Comment by richfitz** [comment]
I can try this when back in at work, _but_ it turns out that postgres foreign tables don't support `COPY` anyway, so I can't use it at all!  The underlying issue (that they're not found by `dbListTables` is possibly still worth fixing, especially if it is used elsewhere

**Comment by krlmlr** [comment]
Can you please double-check the current implementation of `dbListTables()` based on `INFORMATION_SCHEMA`? There is `dbWriteTable(copy = FALSE)`, does that work with foreign tables?

**Comment by richfitz** [comment]
`dbListTables` is finding the foreign table now - thanks!

I'll check the write shortly, but the only foreign table I currently have is not writable

**Comment by krlmlr** [comment]
There are new generics `dbCreateTable()` and `dbAppendTable()` that should make this a non-issue either way.
