### ISSUE TITLE
Install 0.1-7 fails

### ISSUE THREAD

**Issue by mperich** [r-dbi/RPostgres#136]
Installing 0.1-6 via

install_github("rstats-db/RPostgres", ref = "f30fad11b42fbbdb9e5d38cb7159c89dd696105a")

works fine.

## **Error**

rm -f PqConnection.o PqResult.o PqRow.o PqUtils.o RPostgres-init.o RcppExports.o connection.o encode.o encrypt.o result.o RPostgres.dll
"C:/PROGRA~1/R/R-34~1.2/bin/i386/Rscript.exe" "../tools/winlibs.R"
C:/RBuildTools/3.4/mingw_32/bin/g++  -I"C:/PROGRA~1/R/R-34~1.2/include" -DNDEBUG -I../windows/libpq-9.5.2/include -I"C:/Users/Z400Quad/Documents/R/win-library/3.4/BH/include" -I"C:/Users/Z400Quad/Documents/R/win-library/3.4/plogr/include" -I"C:/Users/Z400Quad/Documents/R/win-library/3.4/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c PqConnection.cpp -o PqConnection.o
PqConnection.cpp: In constructor 'PqConnection::PqConnection(std::vector<std::basic_string<char> >, std::vector<std::basic_string<char> >)':
PqConnection.cpp:18:26: error: 'setenv' was not declared in this scope
   setenv("PGTZ", "UTC", 1);
                          ^
make: *** [PqConnection.o] Error 1
Warning: running command 'make -f "Makevars.win" -f "C:/PROGRA~1/R/R-34~1.2/etc/i386/Makeconf" -f "C:/PROGRA~1/R/R-34~1.2/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="RPostgres.dll" OBJECTS="PqConnection.o PqResult.o PqRow.o PqUtils.o RPostgres-init.o RcppExports.o connection.o encode.o encrypt.o result.o"' had status 2
ERROR: compilation failed for package 'RPostgres'
Installation failed: Command failed (1)

## **Session Info**

R version 3.4.2 (2017-09-28)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] rlang_0.1.2        R6_2.2.2           forcats_0.2.0     
 [4] shinyTree_0.2.5    readr_1.1.1        dplyr_0.7.4       
 [7] scales_0.5.0       tidyr_0.7.2        plotly_4.7.1.9000 
[10] stringr_1.2.0      reshape2_1.4.2     ggplot2_2.2.1.9000
[13] DT_0.2             shiny_1.0.5        devtools_1.13.3   
[16] RSQLite_2.0        RPostgreSQL_0.6-2  DBI_0.7-12        

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.13.2      bindr_0.1           compiler_3.4.2     
 [4] git2r_0.19.0        plyr_1.8.4          tools_3.4.2        
 [7] digest_0.6.12       bit_1.1-12          viridisLite_0.2.0  
[10] jsonlite_1.5        memoise_1.1.0       tibble_1.3.4       
[13] gtable_0.2.0        pkgconfig_2.0.1     yaml_2.1.14        
[16] curl_3.0            bindrcpp_0.2        withr_2.1.0.9000   
[19] httr_1.3.1          hms_0.3             htmlwidgets_0.9    
[22] bit64_0.9-7         grid_3.4.2          glue_1.2.0         
[25] data.table_1.10.4-3 purrr_0.2.4         blob_1.1.0         
[28] magrittr_1.5        htmltools_0.3.6     assertthat_0.2.0   
[31] mime_0.5            xtable_1.8-2        colorspace_1.3-2   
[34] httpuv_1.3.5        stringi_1.1.5       lazyeval_0.2.1     
[37] munsell_0.4.3

**Comment by krlmlr** [comment]
Thanks, I replaced the relevant call by a slightly more robust solution.

**Comment by mperich** [comment]
Different error now :(

## **Error**

rm -f PqConnection.o PqResult.o PqRow.o PqUtils.o RPostgres-init.o RcppExports.o connection.o encode.o encrypt.o result.o RPostgres.dll
"C:/PROGRA~1/R/R-34~1.2/bin/i386/Rscript.exe" "../tools/winlibs.R"
C:/RBuildTools/3.4/mingw_32/bin/g++  -I"C:/PROGRA~1/R/R-34~1.2/include" -DNDEBUG -I../windows/libpq-9.5.2/include -I"C:/Users/Z400Quad/Documents/R/win-library/3.4/BH/include" -I"C:/Users/Z400Quad/Documents/R/win-library/3.4/plogr/include" -I"C:/Users/Z400Quad/Documents/R/win-library/3.4/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c PqConnection.cpp -o PqConnection.o
C:/RBuildTools/3.4/mingw_32/bin/g++  -I"C:/PROGRA~1/R/R-34~1.2/include" -DNDEBUG -I../windows/libpq-9.5.2/include -I"C:/Users/Z400Quad/Documents/R/win-library/3.4/BH/include" -I"C:/Users/Z400Quad/Documents/R/win-library/3.4/plogr/include" -I"C:/Users/Z400Quad/Documents/R/win-library/3.4/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c PqResult.cpp -o PqResult.o
C:/RBuildTools/3.4/mingw_32/bin/g++  -I"C:/PROGRA~1/R/R-34~1.2/include" -DNDEBUG -I../windows/libpq-9.5.2/include -I"C:/Users/Z400Quad/Documents/R/win-library/3.4/BH/include" -I"C:/Users/Z400Quad/Documents/R/win-library/3.4/plogr/include" -I"C:/Users/Z400Quad/Documents/R/win-library/3.4/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c PqRow.cpp -o PqRow.o
PqRow.cpp: In member function 'double PqRow::get_date(int)':
PqRow.cpp:113:42: error: 'timegm' was not declared in this scope
   return static_cast<double>(timegm(&date)) / (24.0 * 60 * 60);
                                          ^
PqRow.cpp: In member function 'double PqRow::get_datetime(int, bool)':
PqRow.cpp:149:44: error: 'timegm' was not declared in this scope
     return static_cast<double>(timegm(&date)) + (sec - date.tm_sec);
                                            ^
PqRow.cpp: In member function 'double PqRow::get_date(int)':
PqRow.cpp:114:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
PqRow.cpp: In member function 'double PqRow::get_datetime(int, bool)':
PqRow.cpp:151:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
make: *** [PqRow.o] Error 1
Warning: running command 'make -f "Makevars.win" -f "C:/PROGRA~1/R/R-34~1.2/etc/i386/Makeconf" -f "C:/PROGRA~1/R/R-34~1.2/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="RPostgres.dll" OBJECTS="PqConnection.o PqResult.o PqRow.o PqUtils.o RPostgres-init.o RcppExports.o connection.o encode.o encrypt.o result.o"' had status 2
ERROR: compilation failed for package 'RPostgres'

**Comment by mperich** [comment]
It gets further along now. Bolded what I think is relevant at the bottom for spew readability. 

## **Error**

*** arch - i386
rm -f PqConnection.o PqResult.o PqRow.o PqUtils.o RPostgres-init.o RcppExports.o connection.o encode.o encrypt.o result.o RPostgres.dll
"C:/PROGRA~1/R/R-34~1.2/bin/i386/Rscript.exe" "../tools/winlibs.R"
C:/RBuildTools/3.4/mingw_32/bin/g++  -I"C:/PROGRA~1/R/R-34~1.2/include" -DNDEBUG -I../windows/libpq-9.5.2/include -I"C:/Users/Z400Quad/Documents/R/win-library/3.4/BH/include" -I"C:/Users/Z400Quad/Documents/R/win-library/3.4/plogr/include" -I"C:/Users/Z400Quad/Documents/R/win-library/3.4/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c PqConnection.cpp -o PqConnection.o
C:/RBuildTools/3.4/mingw_32/bin/g++  -I"C:/PROGRA~1/R/R-34~1.2/include" -DNDEBUG -I../windows/libpq-9.5.2/include -I"C:/Users/Z400Quad/Documents/R/win-library/3.4/BH/include" -I"C:/Users/Z400Quad/Documents/R/win-library/3.4/plogr/include" -I"C:/Users/Z400Quad/Documents/R/win-library/3.4/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c PqResult.cpp -o PqResult.o
C:/RBuildTools/3.4/mingw_32/bin/g++  -I"C:/PROGRA~1/R/R-34~1.2/include" -DNDEBUG -I../windows/libpq-9.5.2/include -I"C:/Users/Z400Quad/Documents/R/win-library/3.4/BH/include" -I"C:/Users/Z400Quad/Documents/R/win-library/3.4/plogr/include" -I"C:/Users/Z400Quad/Documents/R/win-library/3.4/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c PqRow.cpp -o PqRow.o
C:/RBuildTools/3.4/mingw_32/bin/g++  -I"C:/PROGRA~1/R/R-34~1.2/include" -DNDEBUG -I../windows/libpq-9.5.2/include -I"C:/Users/Z400Quad/Documents/R/win-library/3.4/BH/include" -I"C:/Users/Z400Quad/Documents/R/win-library/3.4/plogr/include" -I"C:/Users/Z400Quad/Documents/R/win-library/3.4/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c PqUtils.cpp -o PqUtils.o
C:/RBuildTools/3.4/mingw_32/bin/gcc  -I"C:/PROGRA~1/R/R-34~1.2/include" -DNDEBUG -I../windows/libpq-9.5.2/include -I"C:/Users/Z400Quad/Documents/R/win-library/3.4/BH/include" -I"C:/Users/Z400Quad/Documents/R/win-library/3.4/plogr/include" -I"C:/Users/Z400Quad/Documents/R/win-library/3.4/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O3 -Wall  -std=gnu99 -mtune=core2 -c RPostgres-init.c -o RPostgres-init.o
C:/RBuildTools/3.4/mingw_32/bin/g++  -I"C:/PROGRA~1/R/R-34~1.2/include" -DNDEBUG -I../windows/libpq-9.5.2/include -I"C:/Users/Z400Quad/Documents/R/win-library/3.4/BH/include" -I"C:/Users/Z400Quad/Documents/R/win-library/3.4/plogr/include" -I"C:/Users/Z400Quad/Documents/R/win-library/3.4/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c RcppExports.cpp -o RcppExports.o
C:/RBuildTools/3.4/mingw_32/bin/g++  -I"C:/PROGRA~1/R/R-34~1.2/include" -DNDEBUG -I../windows/libpq-9.5.2/include -I"C:/Users/Z400Quad/Documents/R/win-library/3.4/BH/include" -I"C:/Users/Z400Quad/Documents/R/win-library/3.4/plogr/include" -I"C:/Users/Z400Quad/Documents/R/win-library/3.4/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c connection.cpp -o connection.o
C:/RBuildTools/3.4/mingw_32/bin/g++  -I"C:/PROGRA~1/R/R-34~1.2/include" -DNDEBUG -I../windows/libpq-9.5.2/include -I"C:/Users/Z400Quad/Documents/R/win-library/3.4/BH/include" -I"C:/Users/Z400Quad/Documents/R/win-library/3.4/plogr/include" -I"C:/Users/Z400Quad/Documents/R/win-library/3.4/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c encode.cpp -o encode.o
C:/RBuildTools/3.4/mingw_32/bin/g++  -I"C:/PROGRA~1/R/R-34~1.2/include" -DNDEBUG -I../windows/libpq-9.5.2/include -I"C:/Users/Z400Quad/Documents/R/win-library/3.4/BH/include" -I"C:/Users/Z400Quad/Documents/R/win-library/3.4/plogr/include" -I"C:/Users/Z400Quad/Documents/R/win-library/3.4/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c encrypt.cpp -o encrypt.o

**C:/RBuildTools/3.4/mingw_32/bin/g++  -I"C:/PROGRA~1/R/R-34~1.2/include" -DNDEBUG -I../windows/libpq-9.5.2/include -I"C:/Users/Z400Quad/Documents/R/win-library/3.4/BH/include" -I"C:/Users/Z400Quad/Documents/R/win-library/3.4/plogr/include" -I"C:/Users/Z400Quad/Documents/R/win-library/3.4/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c result.cpp -o result.o
C:/RBuildTools/3.4/mingw_32/bin/g++ -shared -s -static-libgcc -o RPostgres.dll tmp.def PqConnection.o PqResult.o PqRow.o PqUtils.o RPostgres-init.o RcppExports.o connection.o encode.o encrypt.o result.o -L../windows/libpq-9.5.2/lib/i386 -lpq -lssl -lcrypto -lwsock32 -lsecur32 -lws2_32 -lgdi32 -lcrypt32 -lwldap32 -Ld:/Compiler/gcc-4.9.3/local330/lib/i386 -Ld:/Compiler/gcc-4.9.3/local330/lib -LC:/PROGRA~1/R/R-34~1.2/bin/i386 -lR
PqRow.o:PqRow.cpp:(.text+0xf90): undefined reference to `_mkgmtime32'
PqRow.o:PqRow.cpp:(.text+0x10fc): undefined reference to `_mkgmtime32'
collect2.exe: error: ld returned 1 exit status**
