### ISSUE TITLE
[feature request] - dbWritetable from local/remote file

### ISSUE THREAD

**Issue by gbisschoff** [r-dbi/RPostgres#137]
Add method for importing data directly from local or remote file. e.g.

dbWriteTable(con,"test","~/test.csv")
using some implementation of:
COPY sample_table
FROM '/path/to/file/test.csv' DELIMITER ',' CSV HEADER;

dbWriteTable(con,"test","sftp://username:passwd@host:port/path/to/file/test.csv")
using some implementation of:
psql -h remotehost -d remote_mydb -U myuser -c "\copy mytable (column1, column2)  from '/path/to/local/file.csv' with delimiter as ','"

**Comment by krlmlr** [comment]
Thanks for the suggestion. I considered it, I think we should focus here on making writes robust and fast for data that is already in R. Interfacing with external data feels out of scope, you can already do it in user code with `dbExecute()` and `system2()`.

Sorry the response took so long.
