### ISSUE TITLE
ERROR:  cannot insert multiple commands into a prepared statement

### ISSUE THREAD

**Issue by mgirlich** [r-dbi/RPostgres#138]
The following code works with `RPostgreSQL` but not with `RPostgres`.

```
dbExecute(
  con,
  "
    CREATE TEMP TABLE n (account_id     integer);
    INSERT INTO n (account_id) VALUES (1);
  "
)
```

```
Error in result_create(conn@ptr, statement) : 
  ERROR:  cannot insert multiple commands into a prepared statement
```

**Comment by krlmlr** [comment]
This is by design. Please use two `dbExecute()` calls.

**Comment by mgirlich** [comment]
Thanks for the answer. That is an easy workaround :-)
I would be interested in the reasons for this design choice. Can you tell me?

**Comment by krlmlr** [comment]
Supporting multiple statements adds a lot of complexity:

- Passing parameters to the queries
- Returning number of affected rows

etc.

**Comment by mgirlich** [comment]
Ah, that makes sense. Thanks a lot.
