### ISSUE TITLE
Int64 should be saved as character

### ISSUE THREAD

**Issue by hadley** [r-dbi/RPostgres#14]

**Comment by Russell-DataScience** [comment]
Alternatively, add bit64 as a dependency and take it in as 64 bit integer?  Regardless, silently wrapping to negative numbers when the stored number is greater than 32 bits probably isn't great.

**Comment by krlmlr** [comment]
https://github.com/rstats-db/DBI/issues/42

**Comment by krlmlr** [comment]
Closing in favor of #94.
