### ISSUE TITLE
Redshift integer in integer64 format

### ISSUE THREAD

**Issue by boxuancui** [r-dbi/RPostgres#141]
The Redshift output of my `count(...)` will always be returned as `integer64`, even if the integer is just in the 100 - 1000 range. This creates some problems, e.g.,

- `scales::comma(x)` will return the number as a string without comma.
- The integer get parsed into something like 1.482197e-323 during `print`/`cat`.

I reverted the version to [v0.1-8](https://github.com/r-dbi/RPostgres/releases/tag/v0.1-8), and everything worked fine. Something in [v0.1-9](https://github.com/r-dbi/RPostgres/releases/tag/v0.1-9) could have caused this behavior.

As suggested in this [SO post](https://stackoverflow.com/questions/45171762/set-dbgetquery-to-return-integer64-as-integer), I casted the output to `int` post query, and it worked. However, in my actual production code, I have 20+ files with 10 ~ 20 count lines from each. I am just wondering if there is a better solution for Redshift instances.

**Comment by krlmlr** [comment]
Thanks. The same seems true for vanilla PostgreSQL, and for RMariaDB. RSQLite doesn't exhibit this behavior, because integers are only converted to 64-bit on demand due to SQLite's weak typing.

I'll provide an opt-out, similar to what the odbc package is doing.

**Comment by boxuancui** [comment]
For some reason, this is still happening for me. I tried both the latest version on GitHub as well as the CRAN repository. Here is a sample output:

	$ var1:integer64 133651 30651 25657 17990 8823 3635 1705 85 
	$ var2:integer64 551899 127984 102186 67921 22335 14028 4789 439 
	$ var3:integer64 617454 137420 109442 70522 23043 14899 5115 452 
	$ var4:integer64 1848710 264221 175832 90603 42871 29936 12787 994 

As you can see, all of the integers are not `int64`.

**Comment by krlmlr** [comment]
Have you tried `dbConnect(..., bigint = "integer")` to opt out?

**Comment by boxuancui** [comment]
My bad. Yes, it works fine.
