### ISSUE TITLE
Install on Mac OS X with Posgres.app

### ISSUE THREAD

**Issue by intheravine** [r-dbi/RPostgres#142]
It does not appear that RPostgres will install on Mac OS X (10.13.1) running Postgres.app (2.1.1). The Postgres.app installs several versions of PostgreSQL: 9.5, 9.6 & 10 with the user able to select which version to use. When I try to install RPostgres I get this message:
`Using PKG_CFLAGS=-I/usr/local/opt/postgresql/include
Using PKG_LIBS=-L/usr/local/opt/{openssl,postgresql}/lib -lpq
------------------------- ANTICONF ERROR ---------------------------
Configuration failed because libpq was not found. Try installing:
 * deb: libpq-dev (Debian, Ubuntu, etc)
 * rpm: postgresql-devel (Fedora, EPEL)
 * rpm: postgreql8-devel, psstgresql92-devel, postgresql93-devel, or postgresql94-devel (Amazon Linux)
 * csw: postgresql_dev (Solaris)
 * brew: postgresql (OSX)
If libpq is already installed, check that either:
(i)  'pkg-config' is in your PATH AND PKG_CONFIG_PATH contains
     a libpq.pc file; or
(ii) 'pg_config' is in your PATH.
If neither can detect , you can set INCLUDE_DIR
and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
--------------------------------------------------------------------`

It doesn't appear that Postgres.app installs a libpq.pc file - in order to install RPostgres must one install PostgreSQL with brew or macports?

**Comment by krlmlr** [comment]
Thanks. Can you please try `brew install postgresql` and then reinstall?

**Comment by intheravine** [comment]
Yep - that works.

**Comment by krlmlr** [comment]
Thanks. I feel the `README.md` could use a brief description of what needs to be installed on what platform. Happy to review a PR.
