### ISSUE TITLE
Windows build on R-devel gives warnings

### ISSUE THREAD

**Issue by krlmlr** [r-dbi/RPostgres#143]
```
In file included from ../windows/libpq-9.5.2/include/postgres_ext.h:26:0,
                 from ../windows/libpq-9.5.2/include/libpq-fe.h:29,
                 from pch.h:2,
                 from DbColumn.cpp:1:
../windows/libpq-9.5.2/include/pg_config_ext.h:8:28: warning: ISO C++ 1998 does not support 'long long' [-Wlong-long]
 #define PG_INT64_TYPE long long int
```

https://win-builder.r-project.org/PRRIeUAp9Z3L/00install.out

@jeroen: Is there a way around this short of saying `SystemRequirements: C++11`? Maybe RPostgres should download libs from the rwinlib repo, too?

**Comment by jeroen** [comment]
Just add `CXX_STD=CXX11` to `src/Makevars.win`.

**Comment by krlmlr** [comment]
Thanks a lot, I keep forgetting about this. Turns out the rwinlib infrastructure is already in place, the `windows/` directory is in `.Rbuildignore`.
