### ISSUE TITLE
can't declare a cursor

### ISSUE THREAD

**Issue by mmuurr** [r-dbi/RPostgres#145]
With the RPostgreSQL package, this pattern works:
```r
dbExecute(conn, "BEGIN")
dbExecute(conn, "DECLARE foo CURSOR FOR SELECT ...")
## loop through dbGetQuery(conn, "FETCH FORWARD {size} FROM foo")
dbExecute(conn, "COMMIT") ## or ROLLBACK
```
But with RPostgres, the `DECLARE ...` cursor statement results in this error:
```
 Error in result_create(conn@ptr, statement) :
   Failed to prepare query: ERROR:  Query cancelled on user's request
```
Any ideas as to why?

**Comment by krlmlr** [comment]
Strange, I can't replicate this problem (with `... FOR SELECT 1`).

Consider using `dbBegin()` and `dbCommit()`, because these functions also track the transaction state and reduce the possibility of a mistake.

**Comment by krlmlr** [comment]
I just saw a bogus "canceling statement due to user request" error on Windows. On what platform have you seen the error?

**Comment by krlmlr** [comment]
Took action to remove possible causes, please open a new issue if problems persist.

**Comment by mmuurr** [comment]
@krlmlr Further digging reveals this seems to be only happening when the 'PostgreSQL' server is actually an Amazon Redshift cluster. I've opened the more specific (with additional details) issue here: #148.
