### ISSUE TITLE
::varchar on quoted strings makes casting necessary

### ISSUE THREAD

**Issue by refik** [r-dbi/RPostgres#146]
I am using the data type [uuid](https://www.postgresql.org/docs/9.1/static/datatype-uuid.html) on a column (`cookie_uuid`) and when I try to filter with that column with `dplyr`, `RPostgres::dbQuoteString()` adds the extra `::varchar` to my filter argument and the query fails with:

```r
Error during wrapup: Failed to prepare query: ERROR:  operator does not exist: uuid = character varying
LINE 3: WHERE ((cookie_uuid = 'd70ae4a9-9b4b-4c9d-aa23-b0ff47faa7a8'...
                            ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
```

with the generated query being:

```r
<SQL>
SELECT *
FROM "auth"
WHERE (("cookie_uuid" = 'd70ae4a9-9b4b-4c9d-aa23-b0ff47faa7a8'::varchar) AND ("created_at" > NOW() at time zone 'utc' - INTERVAL '3 days'))
```

However, if I quote it myself with `dplyr::filter(cookie_uuid == sql("'d70ae4a9-9b4b'")`, it works fine. But this is not safe in my use case. 

Is there something to do about this, or should I change the way I approach the query?

**Comment by krlmlr** [comment]
Thanks for raising this. I'll just remove the `varchar` cast, this doesn't seem to be such a great idea.
