### ISSUE TITLE
should dbRollback warn (vs error) when not within a transaction block?

### ISSUE THREAD

**Issue by mmuurr** [r-dbi/RPostgres#151]
In most SQL applications, ROLLBACK is idempotent. When not in a transaction block some SQL back-ends warn, but PostgreSQL specifically does _not_ error. Here's an example psql session:
```
dbname=> BEGIN;
BEGIN
dbname=> SELECT 1;
 ?column?
----------
        1
(1 row)

dbname=> ROLLBACK;
ROLLBACK
dbname=> ROLLBACK;
WARNING:  there is no transaction in progress
ROLLBACK
```
[This line](https://github.com/r-dbi/RPostgres/blob/d1a4c8063aec20149e1e147bad8d1d58c0d89af4/R/transactions.R#L58) throws an error if not within a transaction, which is unexpected for users familiar with PostgreSQL. Should that be a warning instead?

**Comment by krlmlr** [comment]
It's currently specified to throw an error in DBI, and RPostgres adheres to that spec. As you said, in most SQL backends an unused `ROLLBACK` does no harm, but can we be sure about all SQL backends? Why is it important to have this behavior? I'd rather keep this an error, there is `dbWithTransaction()` that helps writing correct code.

**Comment by mmuurr** [comment]
Not important at all. Just thought it was incongruent with how PostgreSQL operates. Because it's safe, I sometimes issue extraneous `ROLLBACK`s when working interactively, but it's pretty easy to use `try(dbRollback(conn))` for those calls :-)
