### ISSUE TITLE
Using PostgreSQL functions with dplyr::select

### ISSUE THREAD

**Issue by refik** [r-dbi/RPostgres#161]
I have a table with a column called `response` which has the data type `json`. PostgreSQL has nice utility functions for manipulating `json`. One of those functions is [json_populate_recordset](https://www.postgresql.org/docs/9.3/static/functions-json.html) which lets you query a table like this:

| response (json) |
| --- |
| [{"id": 3, "name": "file 1"}, {"id": 5, "name": "file 2"}] | 

in this form:

| id (int) | name (text) |
| --- | --- |
| 3 | file 1 |
| 5 | file 2 |

with a query like this:

```sql
SELECT (json_populate_recordset(null::custom_type, response)).*
FROM "my_table"
```

My approach to generate that query in dplyr was like this:

```r
dplyr::tbl(con, "my_table") %>%
    dplyr::select(json = sql("(json_populate_recordset(null::custom_type, response)).*"))
```

but it fails with:

```r
#> Error: Unknown column `(json_populate_recordset(null::json_type2, response::json->'files')).*` 
```

If it let the use generate this query, there would be no problem:

```sql
SELECT (json_populate_recordset(null::custom_type, response)).* AS "json"
FROM "my_table"
```

I found out that `tidyselect::var_select` has an argument called `.strict` which can be set to `FALSE` for ignoring such errors, but it is as of no use here. I am guessing this issue is not strictly about this package but I was hoping for a guidance in the right direction.

**Comment by krlmlr** [comment]
How does the generated SQL query look like? Please append `%>% dbplyr::sql_render()` to the dplyr pipe.

**Comment by refik** [comment]
@krlmlr When I append `%>% dbplyr::sql_render()` it still fails with the same error (`Unknown column`). This is true for any call to `dplyr::select` with a column name that doesn't exist. Even in the simplest case:

```r
tbl(con, "table") %>%
    select(new_name = "column_that_doesnt_exist") %>%
    sql_render()
#> Error: Unknown column  `column_that_doesnt_exist` 
```

**Comment by krlmlr** [comment]
Can you try `mutate()` instead of `select()`?

**Comment by refik** [comment]
Yes that solved my use case, thank you!

So I just did this instead:
```r
dplyr::tbl(con, "my_table") %>%
    dplyr::mutate(placeholder = sql("(json_populate_recordset(null::custom_type, response)).*"))
```

and got the table:

| response (json) | id (int) | name (text) |
| --- | --- | --- |
| [{"id": 3, "name": "file 1"}, {"id": 5, "name": "file 2"}] | 3 | file 1 |
| [{"id": 3, "name": "file 1"}, {"id": 5, "name": "file 2"}] | 5 | file 2 |

**Comment by refik** [comment]
This would have been ok too if it worked:

```r
dplyr::tbl(con, "my_table") %>%
    dplyr::transmute(sql("*") := sql("(json_populate_recordset(null::custom_type, response)).*"))
#> Error: LHS must be a name or string
```

Without the `sql()` it quotes the `*` (`SELECT "*"`). It it didn't, the query would execute and only give the columns of the populated records.

**Comment by krlmlr** [comment]
Maybe `mutate()` even isn't the best verb here? Perhaps better:

```r
tbl(con, sql("(json_populate_recordset(null::custom_type, response)).*"))
```

**Comment by refik** [comment]
As it is, it doesn't have the table name `my_table` in the picture so it doesn't work this way. I couldn't find the right way to add it in either. 

However, there is one more issue. Before I do the `json_populate_recordset`, I do some filtering on `my_table`. Would it be possible to chain the call to `tbl()` after those?

**Comment by refik** [comment]
@krlmlr One problem of the solution with `mutate()` is that after the populated table is retrieved, no more verbs can be chained to it.

This was the generated query:

```sql
SELECT "response", (json_populate_recordset(null::custom_type, response )).* AS "placeholder"
FROM "my_table"
```

Here is an example that fails when `select()` is chained to it:

```r
dplyr::tbl(con, "my_table") %>%
    dplyr::mutate(placeholder = sql("(json_populate_recordset(null::custom_type, response)).*")) %>%
    dplyr::select("id", "name")
#> Error: Unknown column `id` 
```

I think this is because dplyr doesn't know about the new column names. The only ones that are available to it are `response` and `placeholder`. Also if you try to chain `mutate()`  instead of `select()`, it complains with:

```r
#> Error in result_create(conn@ptr, statement) : 
#>  Failed to prepare query: ERROR:  column "placeholder" does not exist
```
Because it thinks `placeholder` should be in the result set but it isn't.

**Comment by krlmlr** [comment]
That's why I thought `tbl()` might be better. Seems you need full SQL queries in the `from` argument:

``` r
dplyr::tbl(dbplyr::src_memdb(), from = dbplyr::sql("SELECT 1 AS a, 2 AS b"))
#> # Source:   SQL [?? x 2]
#> # Database: sqlite 3.19.3 [:memory:]
#>       a     b
#>   <int> <int>
#> 1     1     2
```

**Comment by refik** [comment]
Thanks. So I think I got to a working solution with your help. I wrote this function to make it easier: 

```r
custom_select <- function(.data, select_expr) {
    random_alias <- paste0(sample(letters, 10, replace = TRUE), collapse = "")
    original_query <- dbplyr::sql_render(.data)
    con <- .data$src$con
    query <- glue("SELECT {select_expr} FROM ({original_query}) \"{random_alias}\"")
    dplyr::tbl(con, from = sql(query))
}
```

Now I am using it like this:

```r
dplyr::tbl(con, "my_table") %>%
    dplyr::filter(hostname = "example.com") %>%
    dplyr::arrange(desc(id)) %>%
    custom_select("(json_populate_recordset(null::custom_type, response )).*")
```

It works as expected. Is this an OK solution for this use case, should I close this issue?

**Comment by krlmlr** [comment]
There currently doesn't seem to be a better way, but I see the utility. Would you mind filing an issue in the dplyr repo? It should be self-contained but still can refer here.
