### ISSUE TITLE
Doesn't work with different schemas

### ISSUE THREAD

**Issue by vikram-rawat** [r-dbi/RPostgres#162]
I have a databse which has different schemas

```
library(DBI)
library(tidyverse)
# Connect to a specific postgres database i.e. Heroku
con1 <- dbConnect(RPostgres::Postgres(),dbname = 'HRMS', 
                 user = 'postgres',
                 password = 'Gurgaon@65')

dbListTables(con1)
```

Produces the result

```
> dbListTables(con1)
character(0)
```

While this code 

```
con2 <- dbConnect(RPostgreSQL::PostgreSQL(),dbname = 'HRMS', 
                 user = 'postgres',
                 password = 'Gurgaon@65')
```

Produces the result

```
dbListTables(con2)
 [1] "bankname"        "attendence"      "designation"     "bin"             "gender"         
 [6] "city"            "districts"       "states"          "employee"        "leaves"         
[11] "salarystructure" "timesheet"  
```
This is the snapshot of the database which has 2 schemas. Kindly make this compatible with DBI and Dplyr. Somehow I am facing a lot of these issues with it.
![image](https://user-images.githubusercontent.com/22342596/34201798-b6467d48-e59b-11e7-8344-df513b07a0d3.png)

**Comment by vikram-rawat** [comment]
same goes for 

`dbReadTable(con2,c("hrms","employee"))
`

as well.

**Comment by krlmlr** [comment]
Thanks. Schema access will be different in RPostgres compared to RPostgreSQL, r-dbi/DBI#24 has details. In the mean time, consider setting the `search_path` database variable manually.

**Comment by krlmlr** [comment]
Schema support now available via `Id()`, see https://dbi.r-dbi.org/reference/id.

**Comment by ahcyip** [comment]
long story short, you can now do this:
dbListObjects(con, prefix = Id(schema = "polk"))
dbListFields(con, name = Id(schema = "polk", table = "polk18"))
