### ISSUE TITLE
Is it possible to connect to remote DB using SSL??

### ISSUE THREAD

**Issue by lalas** [r-dbi/RPostgres#163]
Hello,

I have been searching the web but couldn't find a method that works, so i thought of asking the experts if it's possible, and if so, how.

Cheers

**Comment by krlmlr** [comment]
Thanks. The [relevant docs](https://www.rdocumentation.org/packages/RPostgres/versions/1.0-4/topics/dbDisconnect%2CPqConnection-method) are a bit difficult to find, are they helpful?

**Comment by lalas** [comment]
They were helpful.. passing the extra parameter to dbConnect, sslmode = "require" did the trick.

 Thanks
