### ISSUE TITLE
Minimum PostgreSQL version?

### ISSUE THREAD

**Issue by momeara** [r-dbi/RPostgres#166]
Installing RPostgres from github

    devtools::install_github("r-dbi/RPostgres")

gives me this error

     * installing *source* package ‘RPostgres’ ...
     Found pg_config includedir and libdir (PostgreSQL 8.4.20)!
     This version of libpq is too old! We need at least 9.0!

Is there a plan to support PostgreSQL version `8.4`?

If `9.0` is the minimum required version of PostgreSQL, would it be possible to list that on the package readme?

**Comment by krlmlr** [comment]
Thanks. The info is in the DESCRIPTION, and you "only" need >= 9.0 client libraries. It should work with older PostgreSQL databases, please let me know if it doesn't.
