### ISSUE TITLE
Connection segfault in environment's finalizer

### ISSUE THREAD

**Issue by mmuurr** [r-dbi/RPostgres#167]
This is a bit of a strange issue related to finalized/destroyer timing I think? I've found that if a connection is assigned to an environment and is referenced in that environment's finalizer, when the garbage collector runs the connection reference leads to a segfault. But, it _only_ leads to a segfault if the connection is assigned to the environment _after_ the finalizer has been established.

When using the `RPostgreSQL` or `SQLite` drivers, both versions of the following code examples work fine. With the `RPostgres` driver, however, only the first example works, while the second segfaults.
(Note that I can't easily use `reprex` due to the segfault :-/)

### Working case:

An environment `env` is created, two connections are assigned to `env`, then a finalizer is registered on `env`.

```R
env <- new.env(parent = emptyenv())
env$conn1 <- DBI::dbConnect(RPostgres::Postgres(), ...) ## conn1 params here
env$conn2 <- DBI::dbConnect(RPostgres::Postgres(), ...) ## conn2 params here
reg.finalizer(env, function(env) {
    lapply(unique(as.list(env)), function(x) {
        show(x)
        ##if(inherits(x, "DBIConnection")) try(DBI::dbDisconnect(x))
    })
})

rm(env)
gc()
```
And the (working; redacted) output:
```
 <PqConnection> dbname@host:5432
 <PqConnection> dbname@host:5432
          used (Mb) gc trigger (Mb) max used (Mb)
 Ncells 517059 27.7     940480 50.3   716069 38.3
 Vcells 937311  7.2    1893692 14.5  1272802  9.8
```

### Segfault case:

Here an environment `env` is created, the finalizer is registered, _then_ the two connections are assigned to `env`. In the working case, the connections are assigned first, followed by the finalizer registration.

```R
env <- new.env(parent = emptyenv())
reg.finalizer(env, function(env) {
    lapply(unique(as.list(env)), function(x) {
        show(x)
        ##if(inherits(x, "DBIConnection")) try(DBI::dbDisconnect(x))
    })
})
env$conn1 <- DBI::dbConnect(RPostgres::Postgres(), ...) ## conn1 params here
env$conn2 <- DBI::dbConnect(RPostgres::Postgres(), ...) ## conn2 params here

rm(env)
gc()
```
And an example of a segfault output when `gc()` is called:
```
  *** caught segfault ***
 address 0x128, cause 'memory not mapped'

 Traceback:
  1: .Call(`_RPostgres_connection_info`, con)
  2: connection_info(dbObj@ptr)
  3: dbGetInfo(object)
  4: dbGetInfo(object)
  5: show(x)
  6: show(x)
  7: FUN(X[[i]], ...)
  8: lapply(unique(as.list(env)), function(x) {    show(x)})
  9: (function (env) {    lapply(unique(as.list(env)), function(x) {        show(x)    })})(<environment>)
```

### Other notes

In the code examples above, I'm using `show(x)` just to keep it simple. In a true working example, `show(x)` is replaced by:
```R
if(inherits(x, "DBIConnection")) try(DBI::dbDisconnect(x))
```
... to try to nicely clean-up any lingering DBI connections that I might've forgotten to close explicitly.

**Comment by krlmlr** [comment]
Apparently, the `DbConnection` C++ object is destroyed before the `PqConnection` S4 object. Initial attempts to troubleshoot/fix this went nowhere. 

I've added logging output when these objects are destroyed. In your first example, the C++ objects are destroyed last, in your second example they are destroyed first. I suspect the destruction happens in the finalizer which is added when the `XPtr` object is created during connection. So, finalizers added last seem to run first, and finalization of an external pointer may lead to dangling `EXTERNALPTR` objects. I'd argue this is a bug in R, but we'd need a lower-level reprex to bring this to R-devel.

@romainfrancois: Can we somehow make sure that the finalizer of an environment runs before the finalizer of an `XPtr` contained in this environment?

**Comment by romainfrancois** [comment]
I don't think so. pretty sure it is the other way around.

**Comment by krlmlr** [comment]
Here we observe that the order of running the finalizers depends on the registration order of the finalizers.

**Comment by romainfrancois** [comment]
is that reproducible without the Rcpp layer ?

**Comment by krlmlr** [comment]
I don't know, I don't have time to try it right now.

**Comment by krlmlr** [comment]
Works for me now:

``` r
env <- new.env(parent = emptyenv())
reg.finalizer(env, function(env) {
  lapply(unique(as.list(env)), function(x) {
    show(x)
    ## if(inherits(x, "DBIConnection")) try(DBI::dbDisconnect(x))
  })
})
#> NULL
env$conn1 <- DBI::dbConnect(RPostgres::Postgres()) ## conn1 params here
env$conn2 <- DBI::dbConnect(RPostgres::Postgres()) ## conn2 params here

rm(env)
gc()
#>           used (Mb) gc trigger (Mb) max used (Mb)
#> Ncells  805749 43.1    1267398 67.7  1267398 67.7
#> Vcells 1488190 11.4    8388608 64.0  2832402 21.7
```

<sup>Created on 2020-12-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
