### ISSUE TITLE
Support for dbSendStatement/dbExecute with params?

### ISSUE THREAD

**Issue by jsonbecker** [r-dbi/RPostgres#169]
I was wondering if there is a plan to support dbSendStatement and dbExecute (both of which I use extensively). 

I also use these with params (like dbSendQuery can be used) and currently am using `DBI::sqlInterpolate` and `DBI:dbExecute` for parameterized `INSERT`s.

**Comment by krlmlr** [comment]
Thanks. I'm puzzled, are they broken? They should work, even if the package doesn't provide its own implementation; in this case, the default implementation in DBI is just fine.

**Comment by jsonbecker** [comment]
Huh. It’s not mentioned, but those can be parameterized in DBI, which I didn’t know based on documentation.

My bad. This can be closed.

**Comment by krlmlr** [comment]
Yes, `dbSendQuery()` does support a `params` argument, but it's not documented yet (https://github.com/r-dbi/DBItest/issues/63).
