### ISSUE TITLE
Support for field type citext

### ISSUE THREAD

**Issue by jsonbecker** [r-dbi/RPostgres#170]
Currently get `Unknown field type (60309) in column {column name}` when selecting from a table using citext.

**Comment by etiennebr** [comment]
This should not produce a warning as of 5812667476228861470de51a596f0548f7f8a637. You can install from github to test it.
``` r
devtools::install_github("r-dbi/rpostgres")
library(RPostgres)
conn <- dbConnect(Postgres())
dbExecute(conn, "create extension citext")
x <- dbGetQuery(conn, "select '1'::citext;")

sapply(x, class)
#>      citext 
#> "pq_citext"
```

**Comment by krlmlr** [comment]
@etiennebr: Thanks again for your help with this!
