### ISSUE TITLE
creates error when trying to connect to a different schema

### ISSUE THREAD

**Issue by vikram-rawat** [r-dbi/RPostgres#175]
```
# establishconnection -----------------------------------------------------

psql <- DBI::dbConnect(
    RPostgres::Postgres(),
    host = "localhost",
    port = '5433',
    user = "postgres",
    password = 'Gurgaon@65',
    dbname = 'Vikram'
    # rstudioapi::askForPassword("Database password")
)


# CheckMetadata -----------------------------------------------------------


dbReadTable(psql,c('information_schema','tables'))

```

It generates the error.

```

Error in result_create(conn@ptr, statement) : 
  Expecting a single string value: [type=character; extent=2].

```

Where as this works just fine with Rpostgresql

```

# establishconnection -----------------------------------------------------



psql <- DBI::dbConnect(
    RPostgreSQL::PostgreSQL(),
    host = "localhost",
    port = '5433',
    user = "postgres",
    password = 'Gurgaon@65',
    dbname = 'Vikram'
    # rstudioapi::askForPassword("Database password")
)



# CheckMetadata -----------------------------------------------------------


dbReadTable(psql,c('information_schema','tables'))

````

**Comment by etiennebr** [comment]
This is indeed confusing, but `RPostgres` uses a different way of naming tables and namespace. While `RPostgreSQL` uses `c("schema", "table")`, `RPostgres` uses `DBI::Id(schema = "schema", table = "table")`. 

Since `DBI::Id()` isn't on CRAN yet, you either have to `devtools::github_install("r-dbi/dbi")` or use `SQL("schema"."table")` to replace `Id()`.

**Comment by krlmlr** [comment]
Thanks, Etienne. *DBI* 0.8 already has `Id()`, and I have submitted *RPostgres* 1.1.0 (which supports it) yesterday.

**Comment by Fredo-XVII** [comment]
Just for clarity.  This worked on our Postgres server and put the table in the stated schema.  I wish more examples like this could be found in the documentation for RPostgres.  I have read that doc in and out, and there is nothing that provides an example like the one below.  I have had to piece this together from many different GitHub issues and Stackoverflow...just a little frustrated that I had to spend so much time to get to the code below.  With that said, thank you for adding schema support, that is huge at work at the enterprise level!!

RPostgres::dbWriteTable(con, name = DBI::Id(schema = "landing", table = "iris"), value = iris, overwrite = TRUE)

**Comment by krlmlr** [comment]
@Fredo-XVII: Thanks. I agree that documentation could be better. In the meantime, pull requests are very much welcome ;-)

**Comment by Fredo-XVII** [comment]
@krlmlr Lately I have been thinking about doing some documentation for some packages, funny that you mentioned it.  If start this, do I have to fork the whole repo, or can I just fork the doc/vignette folder? Are there rules on how I am supposed to do this? I have built my own packages, but I have not contributed to an open source project where others are also contributing.

**Comment by krlmlr** [comment]
Thanks. You need to fork the whole repo, but it's not that big. A good place to start is http://happygitwithr.com/.

Please make sure to update the files in `vignettes/`, and `R/`, not in `docs/` or `man/`.

**Comment by krlmlr** [comment]
Will be fixed by https://github.com/r-dbi/DBI/pull/359 in DBI, see https://dbi.r-dbi.org/dev/reference/dbwritetable for an example.
