### ISSUE TITLE
Support importing SQL dumps

### ISSUE THREAD

**Issue by cboettig** [r-dbi/RPostgres#180]
It is somewhat common for database services to provide data dumps as `.sql` files.  To import these into an existing Postgres database we need to use the command line client from outside R, e.g.

```
psql -f datadump.sql
```

It would be great to be able to import such data dumps directly from the R client.

**Comment by krlmlr** [comment]
Thanks. We'd still require an external `psql` utility, but we could:

- offer a wrapper that starts `psql` and pipes a file or a character vector into it
- translate errors to R conditions
- help find it (especially on Windows)

**Comment by krlmlr** [comment]
Is this resolved by arkdb? (Thanks!)

**Comment by cboettig** [comment]
Hmm, unfortunately arkdb doesn't know how to parse a postgres sql file.  It is merely an interface between a pluggable text-reading function, usually something like `read.csv` / `write.csv`, and a DBI interface.  

In some cases we've allowed it to bypass that, e.g. if there's a native bulk importer for `.csv` files for the particular database in question, but in my experience the bulk importers are a lot more fragile than the corresponding R parsers, so those methods fall back on the chunked approach anyway.  

In principle one could add a streamable_table function to arkdb that would handle the `.sql` format, but that would still assume the database client could handle it (i.e. assume external `psql`).

Anyway, I still think we can close this issue out, since in general I don't think .sql dumps are really a reliable, stable text-based exchange format to begin with, and a user committing to postgres is already agreeing to have external software as the server in the first place.  but your call!

**Comment by krlmlr** [comment]
Agree this should be handled by `psql`.
