### ISSUE TITLE
SSL dbConnect Failing

### ISSUE THREAD

**Issue by lusava** [r-dbi/RPostgres#181]
I'm trying to connect to a PostgreSQL data base using SSL with the following code :
```
library(DBI)
con <- dbConnect(RPostgres::Postgres(), 
                 user = user, 
                 password = password, 
                 host = host, 
                 dbname = dbname, 
                 sslmode = "require",
                 port = 5432)
```
The first time I run it I got the following error :
```
Error in connection_create(names(opts), as.vector(opts)) : 
  SSL SYSCALL error: Connection reset by peer (0x00002746/10054)
```
After, all other attempts fail and return this error :
```
Error in result_create(conn@ptr, statement) : 
  Failed to retrieve query result metadata
```
I don't understand what those errors are telling me and what can go wrong with my connection.
Any help would be appreciated ! 
Thank You !

Here is my session info :
```
> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)
> packageVersion("RPostgres")
[1] ‘1.1.0’
> packageVersion("DBI")
[1] ‘0.8’
```

**Comment by krlmlr** [comment]
Thanks. Does this only occur on Windows clients? What do I need to replicate the server setup for testing?

**Comment by peterdesmet** [comment]
I'm also encountering this on Mac.

**Comment by peterdesmet** [comment]
Finally resolved for me by uninstalling the CRAN version and installing the dev version (1.1.1.9002) of the package instead:

```r
devtools::install_github("r-dbi/rpostgres")
```

Then I could make the connection as described in the issue body without the `sslmode = "require"` parameter, which isn't recognized anyway.

**Comment by krlmlr** [comment]
We need to replicate the server setup to make any progress here. Great that reinstalling from GitHub seems to change things, but I don't understand why.

**Comment by daniel-salmon** [comment]
Can we close this?

This looks like it was a server-side issue, namely that SSL was not enabled on whatever database server @lusava was hitting.
