### ISSUE TITLE
per-query bigint option

### ISSUE THREAD

**Issue by r2evans** [r-dbi/RPostgres#182]
Kirill, I'm finally catching up on the `RPostgres` version, thanks for your efforts on this.

I'm confident that the switch to `bit64::integer64` as the default was not made hastily, and I'm glad we have the capability. Since there are many aspects of base R that deal silently-incorrectly with this type, has there been discussion on being able to switch the `bigint=` argument per-query or even per-column?

**Use Case**: pre-existing processes that may rely on significant external code that either have unknown or known-bad compatibility with `bit64::integer64`, but with a connection where 64-bit numbers are needed for some fields. Setting it in `dbConnect` would still be relevant (as the default), but it'd be nice to be able to still use 64-bits when needed.

```r
con <- dbConnect(..., bigint="integer")
dbGetQuery(con, "select 1 as a") # uses the dbConnect option
dbGetQuery(con, "select 1 as a", bigint="integer64") # overrides
```

It's likely going too far, but would anyone see utility in doing it per-column? The workaround until then would be to split the query into two, but this has the potential of being rather inefficient SQL-wise.

```r
dbGetQuery(con, "select 1 as isbig, 2 as isnotbig", bigint=c(isbig="integer64",isnotbig="integer"))
```

where the code might be:

```r
convert_bigint_fields <- function (conn, ret, bigint = conn@bigint) {
    bignms <- names(bigint)
    if (is.null(bignms)) {
      bigint <- setNames(rep(bigint, ncol(ret)), colnames(ret))
    }
    # set all others as default
    bigint[ setdiff(colnames(ret), names(bigint)) ] <- 'default'
    # reorder them
    bigint <- bigint[colnames(ret)]
    is_int64 <- vlapply(ret, inherits, "integer64")
    funs <- list(integer = as.integer, numeric = as.numeric, character = as.character)
    for (funnm in names(funs)) {
      istype <- is_int64 & (bigint == funnm)
      ret[istype] <- lapply(ret[istype], funs[[funnm]])
    }
    ret
}
```

**Comment by r2evans** [comment]
I can see some simplicity in doing self-recovery post-`dbFetch`, certainly, and it keeps things clean from your perspective. I think I fully grok the concept in DBI/137, I'll wait to see how that pans out. Thanks, Kirill.

**Comment by krlmlr** [comment]
Now that we have ALTREP it feels more prudent to focus efforts on providing an ALTREP-based view on the data returned from the database, with conversion as necessary after fetching the data.
