### ISSUE TITLE
dbWriteTable: shift in decimal sign

### ISSUE THREAD

**Issue by damiaan** [r-dbi/RPostgres#186]
I'm quite unsure whether this is an RPostgres problem, but I noticed this strange behavior: using dbWriteTable seems to change the input, shifting the decimal sign; this only happens for some specific numbers it seems...  i hope someone can provide some pointer:

```{r}
> library(DBI)
> library(RPostgres)
> options(scipen=999) ## this did not help
> packageVersion("RPostgres")
[1] ‘1.1.1’
> packageVersion("DBI")
[1] ‘1.0.0’

> mainconnection <- dbConnect(RPostgres::Postgres(), dbname = "pgis", host = "139.191.152.159", port = 5432 ,user = "pguser", password = "xxx")

> thenumber<- -0.0000453740136241442
> thenumber<-as.data.frame(thenumber)
> thenumber
       thenumber
1 -0.00004537401
> dbExecute(mainconnection,"drop table if exists thenumber;")
[1] 0
> dbWriteTable(mainconnection, "thenumber",  value = thenumber, append = FALSE, overwrite=TRUE, row.names = FALSE)
> test<-dbReadTable(mainconnection,"thenumber")
> test
  thenumber
1   -4.5374

## dropping one digit at the end and the result becomes as expected
> thenumber<- -0.000045374013624144
> thenumber<-as.data.frame(thenumber)
> thenumber
       thenumber
1 -0.00004537401
> dbExecute(mainconnection,"drop table if exists thenumber;")
[1] 0
> dbWriteTable(mainconnection, "thenumber",  value = thenumber, append = FALSE, overwrite=TRUE, row.names = FALSE)
> test<-dbReadTable(mainconnection,"thenumber")
> test
     thenumber
1 -0.000045374
```

**Comment by krlmlr** [comment]
Thanks. This now works for me with current dev versions of _DBI_  and _RPostgres_, could you please try again?

**Comment by damiaan** [comment]
I have not been able to replicate this even with the same versions or RPostgres (1.1.1) and DBI (1.0.0); also not with a 100.000 tries with random small numbers. 

This was on a server which I do not maintain, but I do know that since my report it has been transferred to a different physical machine, and also the HDD have been changed to SDD. Perhaps there was a hardware issue at some point?

thanks a bunch anyway for checking!
