### ISSUE TITLE
dbConnect does not work for R3.4.1

### ISSUE THREAD

**Issue by fuhuifang** [r-dbi/RPostgres#188]
I was trying to connect R3.4.1 from RStudio server on AWS EMR cluster to Redshift, and R did not respond for a long time and then it was abnormally terminated due to an unexpected crash. The command I used is 

```
cxn <- dbConnect(RPostgres::Postgres(), host = redshift_login$host, port = redshift_login$port, user = redshift_login$user, password = redshift_login$password, dbname = redshift_login$dbname, sslmode='require')
```

and it works for R 3.5.0 on my local machine. 

I also tried to connect to the default database by `con <- dbConnect(RPostgres::Postgres())`, and it did not respond either.

**Comment by krlmlr** [comment]
Thanks. The "default database" requires an installation of PostgreSQL on a local machine, unlikely to work if you don't have one.

On the RStudio server, can you connect to the RedShift instance from the terminal via `psql` or similar means? This needs a fairly recent version of RStudio, though.

**Comment by fuhuifang** [comment]
No, I was running into this error
`psql: could not connect to server: Connection timed out
	Is the server running on host "XXX.redshift.amazonaws.com" and accepting
	TCP/IP connections on port 5439?`

**Comment by krlmlr** [comment]
Maybe there's a firewall somewhere between the RStudio server and RedShift? The abnormal termination is troublesome, though, I'll leave the issue open.

**Comment by krlmlr** [comment]
We don't currently support Redshift very well. Closing in favor of #215.
