### ISSUE TITLE
A Postgres data source for dbplyr?

### ISSUE THREAD

**Issue by jarodmeng** [r-dbi/RPostgres#195]
`PqConnection` currently works with `dbplyr`, but only using the [default translation](https://github.com/tidyverse/dbplyr/blob/master/R/translate-sql-base.r). It works for most commonly-used functions, but fails when Postgres has slightly different functions.

For instance, `na_if()` is translated to `NULL_IF()` [in dbplyr](https://github.com/tidyverse/dbplyr/blob/master/R/translate-sql-base.r#L132) by default. Postgres has the function `NULLIF()` ([link](https://www.postgresql.org/docs/9.3/static/functions-conditional.html#FUNCTIONS-NULLIF)) instead.

Other database packages include a file that creates a data source for dbplyr and includes database-specific translations (like [this one](https://github.com/r-dbi/bigrquery/blob/master/R/dplyr.R) for BigQuery). Should we have one for RPostgres too?

**Comment by jarodmeng** [comment]
@eweisbrod Does specifying `n` to be an integer by appending `L` work? e.g., `lead(., 2L)` instead of just `lead(., 2)`. I think the default `lead()` translation is `LEAD()` which is correct. What gives the error is the argument type.

**Comment by eweisbrod** [comment]
Thanks @jarodmeng. You are right, the function does work when I add the `L`.  For whatever reason, `lag()` works without the L on Postgres, and both `lag()` and `lead()` work without the L on my local machine. So, I mistakenly thought it was a Postgres issue with `lead()`.

**Comment by krlmlr** [comment]
Thanks. Can you please file an issue in the dbplyr repository? There's nothing _RPostgres_ can do here.
