### ISSUE TITLE
date_trunc() time zone problem in R with DBI and RPostgres packages

### ISSUE THREAD

**Issue by Ivanlong0630** [r-dbi/RPostgres#196]
I am using "RPostgres" and "DBI" packages in RStudio to extract data from Postgres database. UTC is the default time zone in the database.

Here is the problem I encountered. From my perspective,these two queries should have the same output which should be "2018-10-01" (America/Los_Angeles time zone). However, the second one seems to be a result converted from "2018-10-01" (UTC time zone).

`> dbGetQuery(con,"select date_trunc('month',(current_timestamp at time zone 'America/Los_Angeles')::date - interval '1 day')")`
`  date_trunc`
`1 2018-10-01`

`> dbGetQuery(con,"select date_trunc('month',(current_timestamp at time zone 'America/Los_Angeles')::date)")`
`       date_trunc`
`1 2018-09-30 17:00:00`

I am wondering how date_trunc() works in my case. Did I do something wrong? My goal is to generate the first day of a given month based on "America/Los_Angeles" time zone.

Thanks!

**Comment by krlmlr** [comment]
Thanks. `date_trunc()` seems to return a timestamp, you should be able to use `date_trunc(...)::date` .

This question is a better fit for StackOverflow, because it doesn't seem to be relevant for _RPostgres_. (In particular, I'm seeing the same results when running your query with `psql`.)
