### ISSUE TITLE
dbWriteTable shifts numeric values 

### ISSUE THREAD

**Issue by harvey131** [r-dbi/RPostgres#200]
The follow test cases can demonstrate numeric values being shifted by dbWriteTable when copy = T

  ```
# reference value
value <- data.frame(x=-0.000064925595060641, y=-0.00006492559506064059)
  
test_that("insert values with dbExecute", {
  dbExecute(con, "CREATE TEMPORARY TABLE testthat (x numeric NOT NULL, y numeric NOT NULL);")
  dbExecute(con, paste0("INSERT INTO testthat(x, y) values (", value$x, ",", value$y, ");"))
  expect_equal(dbGetQuery(con, "SELECT * FROM testthat"), value)
  dbRemoveTable(con, name = 'testthat')
})

test_that("insert values with dbAppendTable", {
  dbExecute(con, "CREATE TEMPORARY TABLE testthat (x numeric NOT NULL, y numeric NOT NULL);")
  dbAppendTable(con, name = 'testthat', value = value)
  expect_equal(dbGetQuery(con, "SELECT * FROM testthat"), value)
  dbRemoveTable(con, name = 'testthat')
})

test_that("insert values with dbWriteTable(copy = F)", {
  dbWriteTable(con, name = 'testthat', value = value, copy = F)
  expect_equal(dbGetQuery(con, "SELECT * FROM testthat"), value, tolerance = 1e-7) # lower tolerance
  dbRemoveTable(con, name = 'testthat')
})

test_that("insert values with dbWriteTable(append = T, copy = F)", {
  dbExecute(con, "CREATE TEMPORARY TABLE testthat ( x numeric NOT NULL, y numeric NOT NULL);")
  dbWriteTable(con, name = 'testthat', value = value, append = T, copy = F)
  expect_equal(dbGetQuery(con, "SELECT * FROM testthat"), value)
  dbRemoveTable(con, name = 'testthat')
})

test_that("insert values with dbWriteTable(overwrite = T, copy = F)", {
  dbExecute(con, "CREATE TEMPORARY TABLE testthat ( x numeric NOT NULL, y numeric NOT NULL);")
  dbWriteTable(con, name = 'testthat', value = value, overwrite = T, copy = F)
  expect_equal(dbGetQuery(con, "SELECT * FROM testthat"), value, tolerance = 1e-7) # lower tolerance
  dbRemoveTable(con, name = 'testthat')
})

test_that("insert values with dbWriteTable(append = T, copy = T)", {
  dbExecute(con, "CREATE TEMPORARY TABLE testthat ( x numeric NOT NULL, y numeric NOT NULL);")
  dbWriteTable(con, name = 'testthat', value = value, append = T, copy = T)
  # expect_equal(dbGetQuery(con, "SELECT * FROM testthat"), value)
  expect_equal(dbGetQuery(con, "SELECT * FROM testthat"), data.frame(x=value$x, y=value$y*1e5))
  dbRemoveTable(con, name = 'testthat')
})

test_that("insert values with dbWriteTable(append = F, copy = T, field.types=REAL)", {
  dbWriteTable(con, name = 'testthat', value = value, overwrite = T, append = F, copy = T, field.types = c(x='REAL', y='REAL'))
  # expect_equal(dbGetQuery(con, "SELECT * FROM testthat"), value)
  expect_equal(dbGetQuery(con, "SELECT * FROM testthat"), data.frame(x=value$x, y=value$y*1e5), tolerance = 1e-7) # lower tolerance
  dbRemoveTable(con, name = 'testthat')
})

test_that("insert values with dbWriteTable(append = F, copy = T, field.types=NUMERIC)", {
  dbWriteTable(con, name = 'testthat', value = value, overwrite = F, append = F, copy = T, field.types = c(x='NUMERIC', y='NUMERIC'))
  # expect_equal(dbGetQuery(con, "SELECT * FROM testthat"), value)
  expect_equal(dbGetQuery(con, "SELECT * FROM testthat"), data.frame(x=value$x, y=value$y*1e5))
  dbRemoveTable(con, name = 'testthat')
})

# cleanup
dbDisconnect(con)
```

R version 3.5.1 (2018-07-02)   (R Open)
RPostgres ‘1.1.1’

**Comment by cswingle** [comment]
I've been trying to work around this issue as well. I think it's because the Postgres data type chosen via `dbDataType` in `dbWriteTable` is "REAL":

    > dbDataType(con, x)
    [1] "REAL"

Postgres `numeric` would be far more appropriate, but I don't know how to override `dbDataType` in `dbWriteTable` without populating the `field.types` named vector.

**Comment by cswingle** [comment]
This almost works, but the last digit in y seems to be truncated (y ends in 406 rather than 4059)

    df <- data.frame(x=-0.000064925595060641, y=-0.00006492559506064059)
    dbWriteTable(con, name = 'testthat', value = df,
                 field.types = ifelse(dbDataType(con, df) == "REAL",
                                      "NUMERIC",
                                      dbDataType(con, df)))

**Comment by harvey131** [comment]
Unfortunately field.types will not work with dbWriteTable(... append=T).  
The issue will not occur when using dbAppendTable, but this seems slower since it doesn't use copy=T.

A workaround has been to round numeric columns in the data frame prior to the insert:
  data <- rapply(data, round, classes = "numeric", how = "replace", digits = 18)

**Comment by krlmlr** [comment]
There are several places where the observed rounding can happen:

1. When converting from decimal to floating-point in R:

    ``` r
    x <- -0.0000649255950606406
    y <- -0.00006492559506064059
    x - y
    #> [1] 0
    ```

    <sup>Created on 2018-11-26 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

2. When passing the floating-point values to the Postgres database (this would be a bug in _RPostgres_).

3. When storing the data in the database (here, the correct column type needs to be specified at creation time).

@harvey131 observed that `field.types` doesn't work with `append = TRUE` -- yes, the field types need to be supplied at creation. The rounding observed by @cswingle seems to happen already at the R side.

(It would be great to have this documented somewhere, perhaps a blog post on https://r-dbi.org or elsewhere?)

**Comment by harvey131** [comment]
I have updated the test cases to demonstrate the issue only occurs when copy=T with dbWriteTable.

**Comment by harvey131** [comment]
test cases are in [pull request 203 ](https://github.com/r-dbi/RPostgres/pull/203)

**Comment by dkipb** [comment]
> I've been trying to work around this issue as well. I think it's because the Postgres data type chosen via `dbDataType` in `dbWriteTable` is "REAL":
> 
> ```
> > dbDataType(con, x)
> [1] "REAL"
> ```
> Postgres `numeric` would be far more appropriate, but I don't know how to override `dbDataType` in `dbWriteTable` without populating the `field.types` named vector.

I just switched from RpostgreSQL to Rpostgres and it broke all of my dbWriteTable() statements. Has anyone figured out a way to overwrite this? I don't think it's too unreasonable to expect a numeric variable to be numeric in postgres without having to explicitly state the field.type. For now I use this workaround. 

no_real <- function(mydata) {
  data_types <- sapply(mydata, function(x) dbDataType(con_pg, x))
  ifelse(data_types == "REAL", "FLOAT8", data_types)
}

And then calling field.types=no_real(data_set_you_are_loading) in the dbWriteTable() call.
