### ISSUE TITLE
Parameterized queries not working with "?"

### ISSUE THREAD

**Issue by ChuliangXiao** [r-dbi/RPostgres#201]
Parameterized queries at [db.rstudio.com](https://db.rstudio.com/best-practices/run-queries-safely/#parameterized-queries)  
The following query works when using `DBI::dbConnect(odbc::odbc())`,
```
airport <- dbSendQuery(con, "SELECT * FROM airports WHERE faa = ?")
```
, but not `DBI::dbConnect(RPostgres::RPostgres())`.

**Comment by ChuliangXiao** [comment]
@krlmlr Thank you very much.
Just tested. For `DBI::dbConnect(RPostgres::RPostgres())` connection `con`, it works as following.
```
airport <- dbSendQuery(con, "SELECT * FROM airports WHERE faa = $1 or faa = $2")
dbBind(airport, list("GPT", "MSY"))
dbFetch(airport)
```

**Comment by edgararuiz** [comment]
Just opened an Issue for the db.rstudio.com site.  Thanks!
