### ISSUE TITLE
Fails to compile in CentOS7 (fails to find existing libpq-fe.h)

### ISSUE THREAD

**Issue by esaostring** [r-dbi/RPostgres#21]
I try to compile "rstats-db/RPostgres", but it fails to find libpq-fe.h:

```
> devtools::install_github("rstats-db/RPostgres")
Downloading github repo rstats-db/RPostgres@master
Installing RPostgres
'/usr/lib64/R/bin/R' --vanilla CMD INSTALL  \
  '/tmp/Rtmpyy794p/devtoolsc997c6bf0ba/rstats-db-RPostgres-1f09a16'  \
  --library='/home/esa/R/x86_64-redhat-linux-gnu-library/3.1' --install-tests 

* installing *source* package ‘RPostgres’ ...
File libpq-fe.h not found. Please install libpq, e.g: postgresql-devel (rpm) or libpq-dev (deb)
ERROR: configuration failed for package ‘RPostgres’
* removing ‘/home/esa/R/x86_64-redhat-linux-gnu-library/3.1/RPostgres’
Error: Command failed (1)
```

In CentOS7, in order to get Postgresql 9.3 I use pgdg repo, and devel package includes are not in a standard place:

```
[root@localhost bin]# rpm -qil postgresql93-devel | grep libpq-fe
/usr/pgsql-9.3/include/libpq-fe.h
```

And that is also, what is reported by pg_config:

```
[root@localhost bin]# pg_config
BINDIR = /usr/pgsql-9.3/bin
DOCDIR = /usr/share/doc/pgsql
HTMLDIR = /usr/share/doc/pgsql
INCLUDEDIR = /usr/pgsql-9.3/include
[...]
```

**Comment by FlorianEndel** [comment]
In CentOS 5 I had to set these environment variables prior to compiling:
```
export LIBPQ_DIR=/usr/pgsql-9.3/
export LIBRARY_PATH=/usr/pgsql-9.3/lib
```

**Comment by esaostring** [comment]
Ok thanks. This seems to solve the compilation issue!

**Comment by krlmlr** [comment]
Closing for now, please feel free to reopen.

**Comment by dckc** [comment]
I'm using SLES 11, and I get the same symptoms.

I'm somewhat surprised that clues from `pkg-config` don't seem to be consulted.

```
> pkg-config libpq --cflags
-I/usr/include/pgsql 
```

*I don't see how to reopen this issue. I'm not sure I understand the github issue workflow.*

**Comment by krlmlr** [comment]
Thanks. I'll try to replicate this in CentOS. Which version will match SLES 11? (Or is there an easy way to run virtual or dockerized SLES 11?)

**Comment by dckc** [comment]
I hope to get the SLES details to you shortly...

Meanwhile, my solution was to put this in my `~/.R/Makevars`:

```
PKG_CPPFLAGS=$(shell pkg-config libpq --cflags)
PKG_LIBS=$(shell pkg-config libpq --libs)
```

I expect you can use that to replace a lot of custom config stuff. I don't know if it'll work on OS X, but I'd expect it to work in just about all forms of linux.

**Comment by mmuurr** [comment]
Same issue on Amazon Linux.
PostgreSQL's header and library files are (by default) installed here:

```
/usr/include/pgsql/
/usr/lib64/pgsql/
```

... which are both just symlinks to the versioned installation directories.
I've patched my `configure` file in a fork, and am submitting a pull request now...

**Comment by krlmlr** [comment]
@dckc: Thanks for the hint on `pkg-config`. How portable/common is this? Would it be more robust to use [`pg_config`](http://www.postgresql.org/docs/9.3/static/libpq-build.html)?

@mmuurr: Would you mind implementing a more generic solution in #73?

**Comment by dckc** [comment]
`pkg-config` is everywhere, in my experience, though perhaps `pg_config` is to be found wherever the postgres headers are found

googlecounts:
 - pkg-config: About 540,000 results
 - pg_config: About 48,800 results

https://en.wikipedia.org/wiki/Pkg-config

**Comment by mmuurr** [comment]
I've updated the Amazon Linux solution to use pg_config when pkg-config fails (and it thus handles other Linux distros in the more general case).
Since it was a large change, I've closed #73 and would suggest referencing this thread against #81.

**Comment by krlmlr** [comment]
Closing, because #81 is merged now. (Thanks @mmuurr!) Please open a new issue if problems persist.

**Comment by cchris26** [comment]
I could solve the problem in my CentOS 7 only by setting the folder of pg_config in PATH. 
export PATH=$PATH:/usr/pgsql-9.6/bin
