### ISSUE TITLE
dbExistsTable fails on Amazon Redshift

### ISSUE THREAD

**Issue by ilyaminati** [r-dbi/RPostgres#211]
`dbExistsTable` on Redshift returns:

> Error in result_create(conn@ptr, statement) : 
> Failed to prepare query: ERROR:  function generate_subscripts(name[], integer) does not exist
HINT:  No function matches the given name and argument types. You may need to add explicit type casts.

This is likely because `generate_subscripts` is [unsupported on Redshift](http://awsdocs.s3.amazonaws.com/redshift/latest/redshift-dg.pdf).

**Comment by krlmlr** [comment]
Thanks. I'm not familiar with RedShift, can you suggest an alternative query?

https://github.com/r-dbi/RPostgres/blob/e09b0147cbe4bc4c6fb3bf806cab1ee556dc52f9/R/tables.R#L269-L276

**Comment by ilyaminati** [comment]
Sorry, I no longer have access to a Redshift instance, I'm no help here. But what's the reason for doing such a search in the first place? For `dbExistsTable`, is it not sufficient to just query against [PG_TABLE_DEF](https://docs.aws.amazon.com/redshift/latest/dg/r_PG_TABLE_DEF.html)?

**Comment by krlmlr** [comment]
Sure, but will this work for Postgres?

**Comment by krlmlr** [comment]
We don't currently support Redshift very well. Closing in favor of #215.
