### ISSUE TITLE
SSL error: certificate verify failed

### ISSUE THREAD

**Issue by moseleyi** [r-dbi/RPostgres#212]
We have a .Rprofile file with simple function to connect to Redshift. Everybody uses it and it failes on Windows 10 for some reason:

```
DBI::dbConnect(
        RPostgres::Postgres(),
        user = Sys.getenv('REDSHIFT_USER'),
        password = Sys.getenv('REDSHIFT_PASS'),
        host = Sys.getenv('REDSHIFT_HOST'),
        dbname = Sys.getenv('REDSHIFT_DBNAME'),
        port = Sys.getenv('REDSHIFT_PORT'),
        sslmode = 'require',
        sslrootcert = 'C:\\Users\\U\\R\\postgres\\server.crt'
    )
```
I tried `sslmode = verify-full`, `sslmode = verify-ca` but I'm getting the same error:

 ```
Error in connection_create(names(opts), as.vector(opts)) : 
  SSL error: certificate verify failed 
```

**Comment by krlmlr** [comment]
Thanks. What happens with `sslmode = "disable"` ?

**Comment by daniel-salmon** [comment]
@moseleyi:

- Can you verify that SSL is indeed enabled on your Redshift cluster?
- Do you encounter the same error when attempting to connect via `psql` on Windows 10?
- If you attempt to connect with the R `odbc` driver implementation with SSL set to `require` in your configuration are you successful?

**Comment by krlmlr** [comment]
We don't currently support Redshift very well. Closing in favor of #215.
