### ISSUE TITLE
Cannot join tables from other sources

### ISSUE THREAD

**Issue by tanjaclark** [r-dbi/RPostgres#223]
Hello,

I'm connecting to tables in a Redshift database using RPostgres. I'm able to successfully left_join tables that are all from Redshift. However, if I try to left_join a local table to a table in redshift I receive the following error: 

`table_1 %>% left_join(table_2, by = c("key_1" = "key_2"), copy = TRUE) 
`
```
Error in result_create(conn@ptr, statement) : 
  Failed to prepare query: ERROR:  function generate_subscripts(name[], integer) does not exist
HINT:  No function matches the given name and argument types. You may need to add explicit type casts.
```

Using RPostgreSQL instead of RPostgres to connect fixes the issue.

**Comment by krlmlr** [comment]
Thanks. Unfortunately, RPostgres currently doesn't support RedShift very well.

**Comment by krlmlr** [comment]
We don't currently support Redshift very well. Closing in favor of #215.
