### ISSUE TITLE
Implement RStudio Connections Contract

### ISSUE THREAD

**Issue by iangow** [r-dbi/RPostgres#226]
***Feature request:** How difficult would it be to implement the [RStudio Connections Contract](https://rstudio.github.io/rstudio-extensions/connections-contract.html), as has been done for `odbc` [here](https://github.com/rstats-db/odbc/blob/5acc55350e0664002d6281f4659c089911fbd7c3/R/Viewer.R)?

**Comment by dpprdan** [comment]
@iangow See #128 and https://github.com/r-dbi/DBI/issues/211
It seems as if the [connections package](https://github.com/rstudio/connections) is the way forward.

**Comment by iangow** [comment]
Yes, that seems to work. Thanks!

```r
pins::board_register("local")
library(DBI)
pg <- dbConnect(RPostgres::Postgres(), host="192.168.1.192", port=5434L, dbname="crsp")
connections::connection_view(pg)
```
