### ISSUE TITLE
dbListFields does work on Redshift database

### ISSUE THREAD

**Issue by glennmschultz** [r-dbi/RPostgres#228]
I have successfully connected to my Redshift database and I can run the following
dbListTables(conn = conn)
which correctly shows the tables in the database. However,
dbListFields(conn = conn, "mytablename")
does not work and returns the following error

"Error in result_create(conn@ptr, statement) : 
Failed to prepare query: ERROR:  function generate_subscripts(name[], integer) does not exist
HINT:  No function matches the given name and argument types. You may need to add explicit type casts."

when I google the error the best I can come up with is that redshift does not support subscripts.  So, basically, even though R Bloggers suggests Rpostgres as the preferred method perhaps this is not really the case with Redshift as AWS recommends RJDBC.  I suppose either works well dplyr which is my real goal.  However, I am starting a package to work with my Redshift instance and thus would like to have some clarity before I begin.  If there are limitations to Rpostgres then maybe I am better off with RJDBC.

I have a large Redshift database, over 2 terabytes, if the Rpostgres developers need access to a Redshift database to work and test against then I am happy to provide access to what I have for that purpose.
---

Brief description of the problem

```r
# insert reprex here
```

**Comment by krlmlr** [comment]
We don't currently support Redshift very well. Closing in favor of #215.
