### ISSUE TITLE
error: ‘mem_fn’ is not a member of ‘std’ when building on Travis

### ISSUE THREAD

**Issue by jonkeane** [r-dbi/RPostgres#232]
I seem to be having this issue on Travis xenial with oldrel R (example: https://travis-ci.org/jonkeane/dbtest/jobs/620860359#L899), I'm not sure why it's not happening elsewhere.

I suspect that this is a similar issue to https://github.com/r-dbi/RSQLite/issues/304 since https://github.com/r-dbi/RPostgres/blob/master/src/DbDataFrame.cpp#L52 is very similar to before the change that was made at https://github.com/r-dbi/RSQLite/compare/r-2.1.3...r-2.1.4#diff-f830d6d7109dc69475f8059eddbf2d6bL52-R52.

**Comment by krlmlr** [comment]
Thanks, indeed, it's the same file in this repo, with the same problems. Can you please double-check

```r
remotes::install_github("r-dbi/RPostgres@r-1.1.3")
```

which applies the same fix?

**Comment by jonkeane** [comment]
Yup, that works! 

https://travis-ci.org/jonkeane/dbtest/jobs/621213186#L877

**Comment by krlmlr** [comment]
RPostgres 1.1.3 is on CRAN now.
