### ISSUE TITLE
Support LISTEN/NOTIFY

### ISSUE THREAD

**Issue by lentinj** [r-dbi/RPostgres#233]
To be able to receive notifications from Postgres' NOTIFY/LISTEN there needs to be a method to read from ``PQnotifies()``. There's a C example showing how it works here: https://www.postgresql.org/docs/current/libpq-example.html#LIBPQ-EXAMPLE-2

I've made a rough first-pass at implementing it here - https://github.com/lentinj/RPostgres/commit/4b138b1abb1a5e5699502edec79bef34bfe45eef - this adds a ``pqWaitForNotify()`` that sleeps a given number of seconds, or until there's a message.

My main question is where to hang the functionality. Adding a method to DBI, then implementing here seems the wrong thing to do, as this is Postgres specific. Is there an interface you'd prefer instead of what's above?

**Comment by krlmlr** [comment]
Thanks. I'm not familiar with LISTEN/NOTIFY. What's the use case in the context of R and DBI?

**Comment by lentinj** [comment]
LISTEN / NOTIFY is a message queue built-in to PostgreSQL. If one process calls ``NOTIFY grapevine, 'psst'``, then any other processes connected to PostgreSQL that previously called ``LISTEN grapevine`` will get the psst sent to them.

My use-case is fairly standard for LISTEN/NOTIFY, I'd like a bunch of separate R processes being workers that sit around waiting for jobs to be done, so they might look like:-

```
dbSendStatement(db, "LISTEN jobs")
while (TRUE) {
    n <- RPostgres::pqWaitForNotify(db)
    if (!is.null(n)) {
        ... do work ...
    }
}
```

...and another process would call ``dbSendStatement(db2, "NOTIFY jobs, 'new_job'")`` when there's work to be done. I could achieve similar by sleeping for x seconds, then seeing if there's any new work, but polling the database in this manner is less efficient than blocking until there's stuff to do (which is what ``pqWaitForNotify``) does.

Does this help? There's an example in the docs in the above commit showing how you would use this within R.

**Comment by krlmlr** [comment]
This seems pretty unique to Postgres. Perhaps use a `postgres...()` prefix and implement only here?

A pull request would be great.

**Comment by lentinj** [comment]
> This seems pretty unique to Postgres. Perhaps use a postgres...() prefix and implement only here?

Yup, no other database offers anything similar. I had a look at both Perl and Ruby's DBI and they don't bother having a generic method for this.

> A pull request would be great.

Here you go: https://github.com/r-dbi/RPostgres/pull/237
