### ISSUE TITLE
Add function that shows libpq version

### ISSUE THREAD

**Issue by jeroen** [r-dbi/RPostgres#235]
It's useful for debugging to know which version of libpq we are working with. For example `pg_config.h` contains a macro `PG_VERSION_STR` (at least on my libpq) so you could do something like

```c
#include <pg_config.h>

#ifdef PG_VERSION_STR
SEXP version = Rf_mkString(PG_VERSION_STR);
#else
SEXP version = R_NilValue;
#endif

**Comment by krlmlr** [comment]
We now have:

``` r
DBI::dbGetInfo(RPostgres::Postgres())
#> $driver.version
#> [1] '1.1.3.9001'
#> 
#> $client.version
#> [1] '10.0.10'
```

<sup>Created on 2019-12-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

which shows `PQlibVersion()` in the `client.version` component. Does that help?

**Comment by jeroen** [comment]
That doesn't work yet for the CRAN version?

```
> DBI::dbGetInfo(RPostgres::Postgres())
Error in (function (classes, fdef, mtable)  :
  unable to find an inherited method for function ‘dbGetInfo’ for signature ‘"PqDriver"’
```

**Comment by krlmlr** [comment]
Not yet, submitting soon.

**Comment by krlmlr** [comment]
Let me know if we need more diagnostic info, we can add easily to `dbGetInfo()`.

**Comment by jeroen** [comment]
OK thanks. Btw I think you are pasting the version incorrectly, because postgres only has major and minor.

So version `100010` is actually `10.10` and not `10.0.10`.
