### ISSUE TITLE
How can I specify the tablespace

### ISSUE THREAD

**Issue by jjesusfilho** [r-dbi/RPostgres#246]
When creating a table with `dbWriteTable`, I haven't been able to specify the tablespace. Is there a way I can do it?

**Comment by jjesusfilho** [comment]
> You might do `dbExecute(pg, "SET default_tablespace TO your_tablespace")` before using `dbWriteTable`. This is a [connection-level setting](https://www.postgresql.org/docs/current/runtime-config-client.html). I haven't tested this, but I use `dbExecute(pg, "SET search_path TO some_schema")` very frequently before `dbWriteTable` to put the table in the right place.

I do the same, but I wanted to know if it was possible to specify the tablespace. With schema, you can use function `Id()`.

**Comment by krlmlr** [comment]
Is this about where the tables are physically located?

From https://www.postgresql.org/docs/current/manage-ag-tablespaces.html, I'm not sure it's a good fit for `Id()`, the syntax to specify tablespace at creation is shown as

```sql
CREATE TABLE foo(i int) TABLESPACE space1;
```

Is there another way to specify the tablespace?

**Comment by iangow** [comment]
> Is this about where the tables are physically located?

Yes. 

I suspect `dbExecute(pg, "SET default_tablespace TO your_tablespace")` would work for `dbWriteTable` calls afterwards (on the same connection) and thus would be the best way to do things while still using the convenience of that function (`compute()` in `dplyr`, etc., would work in the same way.)

**Comment by iangow** [comment]
In any case, `dbExecute(pg, "SET default_tablespace TO your_tablespace")` "works" as seen in following. Here `cars1` is in one tablespace, while `cars2` is in another (presumably not indicated because it is the default for that database).

``` r
library(dplyr, warn.conflicts = FALSE)
library(DBI)

pg <- dbConnect(RPostgres::Postgres())

rs <- dbExecute(pg, "SET default_tablespace TO pg_default")

dbWriteTable(pg, "cars1", cars, overwrite=TRUE, row.names=FALSE)

rs <- dbExecute(pg, "RESET default_tablespace")

dbWriteTable(pg, "cars2", cars, overwrite=TRUE, row.names=FALSE)
```

<sup>Created on 2020-06-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

```sql
~$ psql -h myhost -d crsp -p 5434
psql (12.3)
SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, bits: 256, compression: off)
Type "help" for help.

crsp=# \d+ cars1
                                       Table "public.cars1"
 Column |       Type       | Collation | Nullable | Default | Storage | Stats target | Description 
--------+------------------+-----------+----------+---------+---------+--------------+-------------
 speed  | double precision |           |          |         | plain   |              | 
 dist   | double precision |           |          |         | plain   |              | 
Tablespace: "pg_default"
Access method: heap

crsp=# \d+ cars2
                                       Table "public.cars2"
 Column |       Type       | Collation | Nullable | Default | Storage | Stats target | Description 
--------+------------------+-----------+----------+---------+---------+--------------+-------------
 speed  | double precision |           |          |         | plain   |              | 
 dist   | double precision |           |          |         | plain   |              | 
Access method: heap

crsp=# 
```

**Comment by krlmlr** [comment]
Where should we document this?
