### ISSUE TITLE
Connection works with RPostgreSQL but not with RPostgres

### ISSUE THREAD

**Issue by OMalytics** [r-dbi/RPostgres#248]
I have a database at AWS that I can access with `RPostgreSQL` but **not** with `RPostgres`.

This works:

```
drv <- dbDriver("PostgreSQL")

con <- DBI::dbConnect(
  drv, 
  dbname = "****",
  host = "****.amazonaws.com", 
  port = 5432,
  user = "****",
  password = "****")
```

This doesn't:

```
drv <- Postgres()

con <- DBI::dbConnect(
  drv, 
  dbname = "****",
  host = "****.amazonaws.com", 
  port = 5432,
  user = "****",
  password = "****")
```
I receive this message instead:
```
Error: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
```

```
> sessionInfo()
R version 4.0.1 (2020-06-06)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.2
```

**Comment by icctr** [comment]
I'm experiencing the same problem.

`R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.5`

**Comment by krlmlr** [comment]
This is weird. Could it be a macOS specific problem? Does it work from a Linux or Windows machine?

**Comment by IndexMic** [comment]
I am experiencing the same problem

**Comment by IndexMic** [comment]
Have you found any way of solving since the op?

**Comment by IndexMic** [comment]
It works now!!!!


This is what I did...

1. **Install and link OpenSSL**
I executed the following commands on my terminal.
`
brew install openssl
brew unlink openssl
export PATH=/usr/local/bin:$PATH
brew link --force openssl
export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"
export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"
brew reinstall postgresql
`

2. **Re install RPostgres from source**
Execute the following in your R session.
`
install.packages("RPostgreSQL", type = "source")
install.packages("RPostgres", type = "source")
`

It now works for me.

On the first step maybe the export paths are different for your computer; however, these paths should be shown in some sort of warning after linking openssl.

**Comment by krlmlr** [comment]
To replicate this I need to find a Mac and provision a Redshift/Postgres database (if it's a Mac issue).

@OMalytics @alexsanjoseph: Can you confirm if a source reinstall fixes the problem?

**Comment by OMalytics** [comment]
Hi @krlmlr, this works for me. Thanks.

**Comment by alexsanjoseph** [comment]
Sorry, not in a situation where I can reproduce this anymore 😞
