### ISSUE TITLE
dbConnect to Azure PG 11 not allowing option "-c role=<rolename>"

### ISSUE THREAD

**Issue by AllenSuttonValocity** [r-dbi/RPostgres#252]
If the dbConnect definition has the option "-c role=<rolename>" specified, Azure Postgres 11 responds with

Error: FATAL:  permission denied to set role "<rolename>"

The rolename used is valid and recognised as valid, otherwise the error reported is 

Error: FATAL:  role "<invalid_rolename>" does not exist

pgAdmin can connect with exactly the same parameters and sets the role on connection to the same target database
---

Cannot specify default postgres role for connection to Azure PG

```r
# insert reprex here
```

**Comment by krlmlr** [comment]
Thanks. Can you please show your call to `dbConnect()`, preferably using the reprex package?

**Comment by dpprdan** [comment]
@AllenSuttonValocity Is `user` you connect with a member of the `role` you want to set?

> The specified *`role_name`* must be a role that the current session user is a member of. (If the session user is a superuser, any role can be selected.)
https://www.postgresql.org/docs/current/sql-set-role.html

`dbConnect()` uses the `SET ROLE` query under the hood. Your error is the same one I get when I try to set a role of which I am not a member of. 

To troubleshoot you could also try to `dbConnect()` without a `role` specified and then `dbExecute(your_con, "SET ROLE {your_target_role}")`.

**Comment by krlmlr** [comment]
Thanks @dpprdan.

Closing because information is missing and no feedback has been provided. For related problems, please open a new issue and add a link to this issue.
