### ISSUE TITLE
Implement RStudio Connections Contract

### ISSUE THREAD

**Issue by warnes** [r-dbi/RPostgres#257]
I would like to use RPostgres connections with the RStudio Connections pane.  

Please implement the Connections Contract (<https://rstudio.github.io/rstudio-extensions/connections-contract.html>)

Thanks!

**Comment by krlmlr** [comment]
Thanks. This works now with the connections package, see https://github.com/rstudio/connections. We could make it easier though (https://github.com/r-dbi/DBI/issues/211).
