### ISSUE TITLE
RPostgres fails to build on FreeBSD

### ISSUE THREAD

**Issue by inferiorhumanorgans** [r-dbi/RPostgres#265]
```r
> install.packages('RPostgres')
[...]
* installing *source* package ‘RPostgres’ ...
** package ‘RPostgres’ successfully unpacked and MD5 sums checked
** using staged installation
./configure: /bin/bash: not found
Warning in system(cmd) : error in running command
ERROR: configuration failed for package ‘RPostgres’
* removing ‘/usr/home/alex/R/amd64-portbld-freebsd12.1-library/4.0/RPostgres’

The downloaded source packages are in
        ‘/tmp/RtmpUsWNX5/downloaded_packages’
Warning message:
In install.packages("RPostgres") :
  installation of package ‘RPostgres’ had non-zero exit status
```

If the configure script is actually a POSIX compliant script without bash-isms `/bin/sh` should probably be used instead as `/bin/bash` is a linux-ism.  Note `RPostgreSQL` installs without complaint.

```sh
$ which bash
/usr/local/bin/bash
```

**Comment by krlmlr** [comment]
Thanks. The `configure` script currently requires `bash`, can you confirm that the package can be installed when `bash` is available?

**Comment by inferiorhumanorgans** [comment]
Well no it doesn't work with bash available because it's hardcoded to look for bash in `/bin`.

**Comment by krlmlr** [comment]
Can you please check if https://github.com/r-dbi/RPostgres/pull/274 works on FreeBSD?

**Comment by krlmlr** [comment]
Merged now.
