### ISSUE TITLE
Confusing error for names in parameterized queries

### ISSUE THREAD

**Issue by mbedward** [r-dbi/RPostgres#266]
This is perhaps related to #199 but hopefully a simpler request.

Presently this code...

```r
dat <- data.frame(foo = 1:3, bar = 4:6)
rs <- dbSendQuery(con, "INSERT INTO sometable (foo, bar) VALUES ($1, $2);")
dbBind(rs, params = dat)
dbClearResults(rs)
```
...provokes an error: 'Named parameters not supported'.

This confused me because the code has positional rather than named placeholders. After looking at the package sources (PgResult.R line 172) I arrived at this work-around:

```r
dbBind(rs, params = unname(dat))
```

Would it cause problems if names were just ignored rather than raising an error? If so, perhaps adding an example of this work-around to the docs would help others.

**Comment by krlmlr** [comment]
Thanks. I agree the error message could be clearer. What wording would be best suited for the problem?

The strictness here is intentional -- named placeholders require named parameters, same with unnamed.
