### ISSUE TITLE
Include views in listed tables?

### ISSUE THREAD

**Issue by currymj** [r-dbi/RPostgres#27]
This is also in hadley/dplyr#1007 (because it comes up when using the `tbl` function). I'm mentioning it here because it seems like RPostgres is going to replace RPostgreSQL eventually and might be able to fix the problem.

RPostgreSQL doesn't return views when using `dbListTables`, which is unexpected for some users. RPostgres uses the same query:

``` SQL
select tablename from pg_tables where schemaname !='information_schema' and schemaname !='pg_catalog';
```

I'm not sure whether RPostgres should just return views along with the tables, or whether there should be a separate `dbListViews` function. But I feel like there should be some way to get at them without writing a raw query.

The following gets both views and "real" tables:

``` SQL
SELECT table_name FROM INFORMATION_SCHEMA.tables WHERE table_schema = ANY (current_schemas(false));
```

**Comment by hadley** [comment]
I think it makes sense to have this on by default.

**Comment by krlmlr** [comment]
`dbListTables()` now also includes views.
