### ISSUE TITLE
getting error while trying to connect to Postgres DB on Heroku using RPostgres 

### ISSUE THREAD

**Issue by sawnaanwas** [r-dbi/RPostgres#289]
I'm using macOS Big Sur, RStudio Version 1.4.1103, R version 4.0.3, and RPostgres version 1.3.1.

I had to reinstall R and Rstudio after R crashed with an error (unable to open the base package). I had to reinstall all R packages I use including RPostgres and DBI. However, now that I run the following code, I receive the following error (for which I did not have any issue before). How can I resolve this? 

 d <- list(host='', dbname='', port='', user='', password='')
  drv <- RPostgres::Postgres()
  con <- RPostgres::dbConnect(drv, dbname=d$dbname, host=d$host, port=d$port,user=d$user, password=d$password)

The error happens when I run the third line. 

Error: FATAL:  no pg_hba.conf entry for host "", user "", database "", SSL off

**Comment by krlmlr** [comment]
Thanks. Can you still connect with `psql` ?

**Comment by sawnaanwas** [comment]
I had always connected using RPostgres and DBI; but I downloaded Postgres.app and was able to connect with `psql`.

**Comment by krlmlr** [comment]
Revisiting the code you posted -- you're initializing `host`, `dbname` and `user` with an empty string. This connects to a local database. Is this intended?

What version of RPostgres did you use before your reinstall?

**Comment by sawnaanwas** [comment]
I deleted the content of `host`, `dbname`, `user`, `port`, and `password`. And I am trying to connect to a Postgres DB on Heroku. Re RPostgres version, I am not sure but probably 1.2.0.

**Comment by krlmlr** [comment]
I'm sorry I couldn't help more. Were you able to resolve this problem?
