### ISSUE TITLE
Recent update causes error on sslmode

### ISSUE THREAD

**Issue by matthewgson** [r-dbi/RPostgres#291]
I reverted my RPostgres back to 1.2.1 because recent version causes error related to ssl.
Here's error I got :

```r
con = dbConnect(Postgres(),
                  host='wrds-pgdata.wharton.upenn.edu',
                  port=9737,
                  dbname='wrds',
                  sslmode='require',
                  user='Matthew')

#sslmode value "require" invalid when SSL support is not compiled in
```

Before rolling back, I tried installing (updating ) openssl and libpq, but didn't help.

**Comment by krlmlr** [comment]
Thanks. What OS are you on?

**Comment by matthewgson** [comment]
I'm using macOS Big Sur version 11.1.

**Comment by Drwhit** [comment]
💯 I am dealing with the same issue, wish I would have seen this bug report hours ago!  I'm on macOS Catalina 10.15.7

We see that when RPostgres 1.3.0 is installed from mran checkpoint 2021-01-18, we can't connect to AWS RDS postgres database. We get the following error:
![image](https://user-images.githubusercontent.com/15175024/106539547-70db1500-64bb-11eb-99c5-7d18fed36fe1.png)

If the same is installed into docker container built on rocker-verse 4.0.3 it works great.  If I explicitly set sslmode to disable here, I get the same error as above. 

Strangely, the RDS database is set to allow but not force SSL connection, so not sure why it is rejecting the connection from mac.

**Comment by ethanrmarkowitz** [comment]
Same issue here.   Reverting to version 1.2.1 solved the problem.   Thank you matthewgson for posting the solution!

**Comment by krlmlr** [comment]
@jeroen: Does this ring a bell?

**Comment by jeroen** [comment]
I think our configure script accidentally used the CRAN version of libpq: https://github.com/R-macos/recipes/blob/master/recipes/libpq

**Comment by jeroen** [comment]
@ethanrmarkowitz @Drwhit @matthewgson could you test if it works with the binary from r-universe?

```r
install.packages("RPostgres", repos = "https://r-dbi.r-universe.dev")
```

Thanks!

**Comment by krlmlr** [comment]
Thanks. Looks like  an installation either from source, or from the package universe as suggested by @jeroen, is the way to go for now.

**Comment by baderstine** [comment]
agree.  1.2.0 was working for me, but now with 1.3.1 it breaks with "Error: sslmode value "require" invalid when SSL support is not compiled in"  this error was one big reason why I switched from RPostgreSQL to RPostgres (RPostgreSQL returns this error as well)

**Comment by jeroen** [comment]
@baderstine did you try the solution above?

**Comment by krlmlr** [comment]
Do we need a user-facing `pgSslSupported()` function that checks if SSL support is compiled in?

We could `#include <pg_config.h>` and then check the value of `USE_OPENSSL`, as per https://stackoverflow.com/a/32643456/946850.

I'll ask CRAN if they consider furnishing their macOS libpq with SSL support.

**Comment by dcaud** [comment]
Any solution to this besides downgrading?

**Comment by krlmlr** [comment]
Looks like an installation either from source, or from the package universe as suggested by @jeroen, is the way to go for now. We're working with CRAN to get libpq 10.0 with SSL mode on the macOS machines.

**Comment by krlmlr** [comment]
RPostgres 1.3.2 is on CRAN now, does SSL work better from macOS?

**Comment by baderstine** [comment]
1.3.2 works for me.
