### ISSUE TITLE
Lighten the dependencies? 

### ISSUE THREAD

**Issue by vspinu** [r-dbi/RPostgres#293]
I wonder if there would be possible to remove some of the heavy dependencies. Particularly BH, even though it's a compile time package, it's 300MB and it imposes some difficulties with deployments to such environments like AWS lambda which is limited to 250MB.

**Comment by krlmlr** [comment]
Thanks. If you install binary packages (with RStudio Package Manager on Linux), you can safely remove BH to get a working solution today. With C++11, which is pretty standard in recent R versions, it should be possible to avoid BH altogether -- it's used mostly for smart pointers. Would you like to contribute?

**Comment by vspinu** [comment]
I would love to, but currently I am extremely busy ATM. It's not high priority I guess. If this can wait for half a year I would be happy to give it a try in the summer.

**Comment by vspinu** [comment]
I have had a quick look at the code base. It's a bit more than shared pointers:

```
DbDataFrame.h
4:#include <boost/container/stable_vector.hpp>
5:#include <boost/scoped_ptr.hpp>

PqColumnDataSource.cpp
2:#include <boost/lexical_cast.hpp>

DbColumn.h
7:#include <boost/shared_ptr.hpp>
8:#include <boost/ptr_container/ptr_vector.hpp>

DbConnection.h
4:#include <boost/noncopyable.hpp>
5:#include <boost/shared_ptr.hpp>

DbResult.h
4:#include <boost/noncopyable.hpp>
5:#include <boost/shared_ptr.hpp>
6:#include <boost/scoped_ptr.hpp>

DbDataFrame.cpp
7:#include <boost/bind.hpp>
8:#include <boost/range/algorithm_ext/for_each.hpp>

PqResultImpl.h
4:#include <boost/noncopyable.hpp>
5:#include <boost/shared_ptr.hpp>
```

From what I can tell moving shared_ptr, scoped_ptr, ptr_vector, noncopyable, bind and for_each shouldn't be hard. lexical_cast is used once and there is a drop in `atoll` in c++11. The biggest problem to my eye is  [stable_vector](https://github.com/r-dbi/RPostgres/blob/78a71f748162b479c7afb7c980186304e6f2b6ae/src/DbDataFrame.h#L15) which seems to be right at the core of the functionality with maybe deep implications. 

In any case I would estimate that I might need 1-2 days to just sink into the codebase + 1-2 days to make the implementation. This is a bit over my head ATM. I might pick this up in summer as a learning experience if you don't beat me to it. The project does seems like a lot of fun with a lot of good things to learn on my side.

**Comment by krlmlr** [comment]
BH is gone now.

**Comment by vspinu** [comment]
Thanks! I see you moved BH inline. Looks good. Surprisingly it resulted into 1.5MB package archive only.
