### ISSUE TITLE
dbWriteTable - not atomic; should it be?

### ISSUE THREAD

**Issue by mmuurr** [r-dbi/RPostgres#307]
As far as I can tell, `dbWriteTable` is not (transactionally) atomic; should it be?
Obviously we can wrap it a transaction block from R code, but I'm curious if this was an intentional choice for some particular reasons (that I'd love to learn about!).

I couldn't find DBI documentation one-way-or-the-other about `dbWriteTable` and SQL transactions, so also perhaps it'd be useful to update the help pages to specifically mention this?

**Comment by krlmlr** [comment]
Thanks. I think it should be atomic, that's what we strive for at least. Not all DBMS allow transactions across DDL and DML, though.
