### ISSUE TITLE
Re-licensing RPostgres

### ISSUE THREAD

**Issue by hadley** [r-dbi/RPostgres#312]
We are systematically re-licensing tidyverse, r-lib, and now (where possible) r-dbi packages to use the MIT license, to make our package licenses as clear and permissive as possible. To do so, we need the approval of all copyright holders, which I have found by reviewing contributions from all all non-RStudio [contributors](https://github.com/r-dbi/RPostgres/graphs/contributors). @Altons, @ateucher, @baderstine, @baileych, @etiennebr, @harvey131, @imlijunda, @JackStat, @jaredk-porch, @jeroen, @lentinj, @mmuurr, @oz-r, @robertzk, @thrasibule, @trafficonese, @troels, @TSchiefer, @zozlak, would you permit us to re-license RPostgres with the MIT license? If so, please comment "I agree" below.
​
* [x] [@Altons](https://github.com/r-dbi/RPostgres/commits?author=Altons)  
* [x] [@ateucher](https://github.com/r-dbi/RPostgres/commits?author=ateucher)  
* [x] [@baderstine](https://github.com/r-dbi/RPostgres/commits?author=baderstine)  
* [x] [@baileych](https://github.com/r-dbi/RPostgres/commits?author=baileych)  
* [x] [@etiennebr](https://github.com/r-dbi/RPostgres/commits?author=etiennebr)  
* [x] [@harvey131](https://github.com/r-dbi/RPostgres/commits?author=harvey131)  
* [x] [@imlijunda](https://github.com/r-dbi/RPostgres/commits?author=imlijunda)  
* [ ] [@JackStat](https://github.com/r-dbi/RPostgres/commits?author=JackStat)  
* [ ] [@jaredk-porch](https://github.com/r-dbi/RPostgres/commits?author=jaredk-porch)  
* [x] [@jeroen](https://github.com/r-dbi/RPostgres/commits?author=jeroen)  
* [x] [@lentinj](https://github.com/r-dbi/RPostgres/commits?author=lentinj)  
* [x] [@mmuurr](https://github.com/r-dbi/RPostgres/commits?author=mmuurr)  
* [x] [@oz-r](https://github.com/r-dbi/RPostgres/commits?author=oz-r)  
* [x] [@robertzk](https://github.com/r-dbi/RPostgres/commits?author=robertzk)  
* [x] [@thrasibule](https://github.com/r-dbi/RPostgres/commits?author=thrasibule)  
* [x] [@trafficonese](https://github.com/r-dbi/RPostgres/commits?author=trafficonese)  
* [x] [@troels](https://github.com/r-dbi/RPostgres/commits?author=troels)  
* [x] [@TSchiefer](https://github.com/r-dbi/RPostgres/commits?author=TSchiefer)  
* [x] [@zozlak](https://github.com/r-dbi/RPostgres/commits?author=zozlak)

**Comment by harvey131** [comment]
I agree

**Comment by jeroen** [comment]
I agree

**Comment by robertzk** [comment]
I agree.

**Comment by oz-r** [comment]
I agree.

On Tue, Jul 6, 2021 at 12:37 Hadley Wickham ***@***.***>
wrote:

> We are systematically re-licensing tidyverse, r-lib, and now (where
> possible) r-dbi packages to use the MIT license, to make our package
> licenses as clear and permissive as possible. To do so, we need the
> approval of all copyright holders, which I have found by reviewing
> contributions from all all non-RStudio contributors
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_r-2Ddbi_RPostgres_graphs_contributors&d=DwMFaQ&c=WvG0b4OO_RKn2Vh2-dPugA&r=Cfib0vLgl57EcKb5kqMLfkGUPwb3Ua04KZbqfr_IaFs&m=TDDSpWUiIrNTgLMjiCAngCNqiN1t4zmIHWvxj7NxuvY&s=u7IhgNQQ4ca-_pKnu5CK4eeMCS216a-8ZOwJLnKflRU&e=>.
> @Altons
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Altons&d=DwMFaQ&c=WvG0b4OO_RKn2Vh2-dPugA&r=Cfib0vLgl57EcKb5kqMLfkGUPwb3Ua04KZbqfr_IaFs&m=TDDSpWUiIrNTgLMjiCAngCNqiN1t4zmIHWvxj7NxuvY&s=PrQ4sqiOgOnHXGPSxSTnjQ7iGztdKexo_AYcwU9_txs&e=>,
> @ateucher
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ateucher&d=DwMFaQ&c=WvG0b4OO_RKn2Vh2-dPugA&r=Cfib0vLgl57EcKb5kqMLfkGUPwb3Ua04KZbqfr_IaFs&m=TDDSpWUiIrNTgLMjiCAngCNqiN1t4zmIHWvxj7NxuvY&s=zBT0lSHcKMgBYIK-lE1R18MGU4VtHO8RXlRH4RmT4z8&e=>,
> @baderstine
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_baderstine&d=DwMFaQ&c=WvG0b4OO_RKn2Vh2-dPugA&r=Cfib0vLgl57EcKb5kqMLfkGUPwb3Ua04KZbqfr_IaFs&m=TDDSpWUiIrNTgLMjiCAngCNqiN1t4zmIHWvxj7NxuvY&s=C0r_s43BUCqN_9qxrYsyk7qLMkJGC_xZxxPZ1AiigCE&e=>,
> @baileych
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_baileych&d=DwMFaQ&c=WvG0b4OO_RKn2Vh2-dPugA&r=Cfib0vLgl57EcKb5kqMLfkGUPwb3Ua04KZbqfr_IaFs&m=TDDSpWUiIrNTgLMjiCAngCNqiN1t4zmIHWvxj7NxuvY&s=Cn-xo_WEbDRWs1wqMKHcU8BXLySPR3orrUjKsyMiNwk&e=>,
> @etiennebr
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_etiennebr&d=DwMFaQ&c=WvG0b4OO_RKn2Vh2-dPugA&r=Cfib0vLgl57EcKb5kqMLfkGUPwb3Ua04KZbqfr_IaFs&m=TDDSpWUiIrNTgLMjiCAngCNqiN1t4zmIHWvxj7NxuvY&s=vqtZE9M3N1Max2fC83Lb7ZJlxxeH1bawIKo3FlSe3Cg&e=>,
> @harvey131
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_harvey131&d=DwMFaQ&c=WvG0b4OO_RKn2Vh2-dPugA&r=Cfib0vLgl57EcKb5kqMLfkGUPwb3Ua04KZbqfr_IaFs&m=TDDSpWUiIrNTgLMjiCAngCNqiN1t4zmIHWvxj7NxuvY&s=vNXxRO3jmgVLpV4TehDcu6nNFKT4FBw-CYecIrMlG6A&e=>,
> @imlijunda
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_imlijunda&d=DwMFaQ&c=WvG0b4OO_RKn2Vh2-dPugA&r=Cfib0vLgl57EcKb5kqMLfkGUPwb3Ua04KZbqfr_IaFs&m=TDDSpWUiIrNTgLMjiCAngCNqiN1t4zmIHWvxj7NxuvY&s=rheT9xtBSXu0gAp7cKi9Isko8PFVJhSE1aA1D7GLBkM&e=>,
> @JackStat
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_JackStat&d=DwMFaQ&c=WvG0b4OO_RKn2Vh2-dPugA&r=Cfib0vLgl57EcKb5kqMLfkGUPwb3Ua04KZbqfr_IaFs&m=TDDSpWUiIrNTgLMjiCAngCNqiN1t4zmIHWvxj7NxuvY&s=KcoY56m213ZQR3Ug22HNMs6DS3pyXaLm3DHC28bHYU0&e=>,
> @jaredk-porch
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_jaredk-2Dporch&d=DwMFaQ&c=WvG0b4OO_RKn2Vh2-dPugA&r=Cfib0vLgl57EcKb5kqMLfkGUPwb3Ua04KZbqfr_IaFs&m=TDDSpWUiIrNTgLMjiCAngCNqiN1t4zmIHWvxj7NxuvY&s=GOEyn3XJGR4bJVA0CYBhRpd44smn-pDZmV4T14SQAI8&e=>,
> @jeroen
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_jeroen&d=DwMFaQ&c=WvG0b4OO_RKn2Vh2-dPugA&r=Cfib0vLgl57EcKb5kqMLfkGUPwb3Ua04KZbqfr_IaFs&m=TDDSpWUiIrNTgLMjiCAngCNqiN1t4zmIHWvxj7NxuvY&s=Agam2aaqpBjsa-VhtCNyvd5cfb7tm1cXy8UwskeUX5s&e=>,
> @lentinj
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_lentinj&d=DwMFaQ&c=WvG0b4OO_RKn2Vh2-dPugA&r=Cfib0vLgl57EcKb5kqMLfkGUPwb3Ua04KZbqfr_IaFs&m=TDDSpWUiIrNTgLMjiCAngCNqiN1t4zmIHWvxj7NxuvY&s=xdYrCdbgEZcpzmRB5NNTLsozWlwUVL5u8p4gnMYwrNU&e=>,
> @mmuurr
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_mmuurr&d=DwMFaQ&c=WvG0b4OO_RKn2Vh2-dPugA&r=Cfib0vLgl57EcKb5kqMLfkGUPwb3Ua04KZbqfr_IaFs&m=TDDSpWUiIrNTgLMjiCAngCNqiN1t4zmIHWvxj7NxuvY&s=3MzQHWFGQyJGVUkHwz-y6yca-bBKR45Q9xfmakN0olI&e=>,
> @oz-r
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_oz-2Dr&d=DwMFaQ&c=WvG0b4OO_RKn2Vh2-dPugA&r=Cfib0vLgl57EcKb5kqMLfkGUPwb3Ua04KZbqfr_IaFs&m=TDDSpWUiIrNTgLMjiCAngCNqiN1t4zmIHWvxj7NxuvY&s=UFptWpLPjhSUjRNY6kI2SCFLAsLzbAd0S673Wh7WqcY&e=>,
> @robertzk
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_robertzk&d=DwMFaQ&c=WvG0b4OO_RKn2Vh2-dPugA&r=Cfib0vLgl57EcKb5kqMLfkGUPwb3Ua04KZbqfr_IaFs&m=TDDSpWUiIrNTgLMjiCAngCNqiN1t4zmIHWvxj7NxuvY&s=bQ1m3nPQZt6sx9v9vIDcxIUwUEJcXu4iaDwNFAKdR4M&e=>,
> @thrasibule
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_thrasibule&d=DwMFaQ&c=WvG0b4OO_RKn2Vh2-dPugA&r=Cfib0vLgl57EcKb5kqMLfkGUPwb3Ua04KZbqfr_IaFs&m=TDDSpWUiIrNTgLMjiCAngCNqiN1t4zmIHWvxj7NxuvY&s=C9hwqOfpfraAfLAgygsmWlBlCQmJRQwc5UJ7mbbaa2A&e=>,
> @trafficonese
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_trafficonese&d=DwMFaQ&c=WvG0b4OO_RKn2Vh2-dPugA&r=Cfib0vLgl57EcKb5kqMLfkGUPwb3Ua04KZbqfr_IaFs&m=TDDSpWUiIrNTgLMjiCAngCNqiN1t4zmIHWvxj7NxuvY&s=lSZUfT90vjl8z4VPlDXbqQvn-9ZsrtJokv2Iz9ZIlqo&e=>,
> @troels
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_troels&d=DwMFaQ&c=WvG0b4OO_RKn2Vh2-dPugA&r=Cfib0vLgl57EcKb5kqMLfkGUPwb3Ua04KZbqfr_IaFs&m=TDDSpWUiIrNTgLMjiCAngCNqiN1t4zmIHWvxj7NxuvY&s=yJwhEh1XrUqonLiPPlpz-FCpZs2iYz8uNDfoee3TkfA&e=>,
> @TSchiefer
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_TSchiefer&d=DwMFaQ&c=WvG0b4OO_RKn2Vh2-dPugA&r=Cfib0vLgl57EcKb5kqMLfkGUPwb3Ua04KZbqfr_IaFs&m=TDDSpWUiIrNTgLMjiCAngCNqiN1t4zmIHWvxj7NxuvY&s=k5w16mm6QiE-XKYogSfvd9Tii_jFJD7AFm5XWmlx82g&e=>,
> @zozlak
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_zozlak&d=DwMFaQ&c=WvG0b4OO_RKn2Vh2-dPugA&r=Cfib0vLgl57EcKb5kqMLfkGUPwb3Ua04KZbqfr_IaFs&m=TDDSpWUiIrNTgLMjiCAngCNqiN1t4zmIHWvxj7NxuvY&s=j8GQSmtl3kGs9ahMPMi_3CIDQZVsR4dGxlmcYrkZeaM&e=>,
> would you permit us to re-license RPostgres with the MIT license? If so,
> please comment "I agree" below.
> ​
>
>    - @Altons
>    <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_r-2Ddbi_RPostgres_commits-3Fauthor-3DAltons&d=DwMFaQ&c=WvG0b4OO_RKn2Vh2-dPugA&r=Cfib0vLgl57EcKb5kqMLfkGUPwb3Ua04KZbqfr_IaFs&m=TDDSpWUiIrNTgLMjiCAngCNqiN1t4zmIHWvxj7NxuvY&s=TT9lG1gj2zPpQ8UgwX3iphoAS6dGR29ePS8pJ9Ac3EM&e=>
>    - @ateucher
>    <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_r-2Ddbi_RPostgres_commits-3Fauthor-3Dateucher&d=DwMFaQ&c=WvG0b4OO_RKn2Vh2-dPugA&r=Cfib0vLgl57EcKb5kqMLfkGUPwb3Ua04KZbqfr_IaFs&m=TDDSpWUiIrNTgLMjiCAngCNqiN1t4zmIHWvxj7NxuvY&s=aLHZUo6MiXPkOi9caw_vNy2n5l_VJuy9QSA5yiSlLWI&e=>
>    - @baderstine
>    <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_r-2Ddbi_RPostgres_commits-3Fauthor-3Dbaderstine&d=DwMFaQ&c=WvG0b4OO_RKn2Vh2-dPugA&r=Cfib0vLgl57EcKb5kqMLfkGUPwb3Ua04KZbqfr_IaFs&m=TDDSpWUiIrNTgLMjiCAngCNqiN1t4zmIHWvxj7NxuvY&s=JgpgrreG2LmrNP3oyQif2BlZiJ7OJc1hMPAfKnUWMEs&e=>
>    - @baileych
>    <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_r-2Ddbi_RPostgres_commits-3Fauthor-3Dbaileych&d=DwMFaQ&c=WvG0b4OO_RKn2Vh2-dPugA&r=Cfib0vLgl57EcKb5kqMLfkGUPwb3Ua04KZbqfr_IaFs&m=TDDSpWUiIrNTgLMjiCAngCNqiN1t4zmIHWvxj7NxuvY&s=OmnYJiPOBb9_YtqL7p7Pz3SyklLaItLXAsgX_KpBWhs&e=>
>    - @etiennebr
>    <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_r-2Ddbi_RPostgres_commits-3Fauthor-3Detiennebr&d=DwMFaQ&c=WvG0b4OO_RKn2Vh2-dPugA&r=Cfib0vLgl57EcKb5kqMLfkGUPwb3Ua04KZbqfr_IaFs&m=TDDSpWUiIrNTgLMjiCAngCNqiN1t4zmIHWvxj7NxuvY&s=6peNeR7umJcUnOaTd0CBvdc08gqqAaryz6kbqBX973g&e=>
>    - @harvey131
>    <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_r-2Ddbi_RPostgres_commits-3Fauthor-3Dharvey131&d=DwMFaQ&c=WvG0b4OO_RKn2Vh2-dPugA&r=Cfib0vLgl57EcKb5kqMLfkGUPwb3Ua04KZbqfr_IaFs&m=TDDSpWUiIrNTgLMjiCAngCNqiN1t4zmIHWvxj7NxuvY&s=LdSwh2F_rCG3TkWUEK5x6a9UOJA1V3WrEeA1Y8GMITY&e=>
>    - @imlijunda
>    <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_r-2Ddbi_RPostgres_commits-3Fauthor-3Dimlijunda&d=DwMFaQ&c=WvG0b4OO_RKn2Vh2-dPugA&r=Cfib0vLgl57EcKb5kqMLfkGUPwb3Ua04KZbqfr_IaFs&m=TDDSpWUiIrNTgLMjiCAngCNqiN1t4zmIHWvxj7NxuvY&s=sCPFFOxNd2bleaEhYtz2I93MbxtXtyUMP10rMYBA4bk&e=>
>    - @JackStat
>    <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_r-2Ddbi_RPostgres_commits-3Fauthor-3DJackStat&d=DwMFaQ&c=WvG0b4OO_RKn2Vh2-dPugA&r=Cfib0vLgl57EcKb5kqMLfkGUPwb3Ua04KZbqfr_IaFs&m=TDDSpWUiIrNTgLMjiCAngCNqiN1t4zmIHWvxj7NxuvY&s=WgJrEA3YlyT3vGfVcDLuWMn1xxRAJGu7mNeMWDPpeTQ&e=>
>    - @jaredk-porch
>    <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_r-2Ddbi_RPostgres_commits-3Fauthor-3Djaredk-2Dporch&d=DwMFaQ&c=WvG0b4OO_RKn2Vh2-dPugA&r=Cfib0vLgl57EcKb5kqMLfkGUPwb3Ua04KZbqfr_IaFs&m=TDDSpWUiIrNTgLMjiCAngCNqiN1t4zmIHWvxj7NxuvY&s=qqgexfpQth0taiwbWoQKAZNGOZVgjBg6IuKBomrtML0&e=>
>    - @jeroen
>    <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_r-2Ddbi_RPostgres_commits-3Fauthor-3Djeroen&d=DwMFaQ&c=WvG0b4OO_RKn2Vh2-dPugA&r=Cfib0vLgl57EcKb5kqMLfkGUPwb3Ua04KZbqfr_IaFs&m=TDDSpWUiIrNTgLMjiCAngCNqiN1t4zmIHWvxj7NxuvY&s=RZWlwad4iIJQC4SjeMs3Mv3t3kFUKgPRFyIJ1vuBAss&e=>
>    - @lentinj
>    <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_r-2Ddbi_RPostgres_commits-3Fauthor-3Dlentinj&d=DwMFaQ&c=WvG0b4OO_RKn2Vh2-dPugA&r=Cfib0vLgl57EcKb5kqMLfkGUPwb3Ua04KZbqfr_IaFs&m=TDDSpWUiIrNTgLMjiCAngCNqiN1t4zmIHWvxj7NxuvY&s=CCOwckQKNv4W1wBOGFARYLk6HlCj3hYKY3O5Y41g54o&e=>
>    - @mmuurr
>    <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_r-2Ddbi_RPostgres_commits-3Fauthor-3Dmmuurr&d=DwMFaQ&c=WvG0b4OO_RKn2Vh2-dPugA&r=Cfib0vLgl57EcKb5kqMLfkGUPwb3Ua04KZbqfr_IaFs&m=TDDSpWUiIrNTgLMjiCAngCNqiN1t4zmIHWvxj7NxuvY&s=mnWB8VrmfYnpwsXCP7PdlsGe7eBLXfVZD5eh0jVA51o&e=>
>    - @oz-r
>    <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_r-2Ddbi_RPostgres_commits-3Fauthor-3Doz-2Dr&d=DwMFaQ&c=WvG0b4OO_RKn2Vh2-dPugA&r=Cfib0vLgl57EcKb5kqMLfkGUPwb3Ua04KZbqfr_IaFs&m=TDDSpWUiIrNTgLMjiCAngCNqiN1t4zmIHWvxj7NxuvY&s=w5_rSclrrWXi8l-5vEmlK6ySUqE2c3MQrrqCOz4wXwY&e=>
>    - @robertzk
>    <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_r-2Ddbi_RPostgres_commits-3Fauthor-3Drobertzk&d=DwMFaQ&c=WvG0b4OO_RKn2Vh2-dPugA&r=Cfib0vLgl57EcKb5kqMLfkGUPwb3Ua04KZbqfr_IaFs&m=TDDSpWUiIrNTgLMjiCAngCNqiN1t4zmIHWvxj7NxuvY&s=XHeu2k3GMLYlRNY3yagbpnrvVjIdx4jXN8L3FIEelEg&e=>
>    - @thrasibule
>    <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_r-2Ddbi_RPostgres_commits-3Fauthor-3Dthrasibule&d=DwMFaQ&c=WvG0b4OO_RKn2Vh2-dPugA&r=Cfib0vLgl57EcKb5kqMLfkGUPwb3Ua04KZbqfr_IaFs&m=TDDSpWUiIrNTgLMjiCAngCNqiN1t4zmIHWvxj7NxuvY&s=NxM5BgXGf6yYhi37XpcVCtTK96bRVQItiYFUCdusSFI&e=>
>    - @trafficonese
>    <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_r-2Ddbi_RPostgres_commits-3Fauthor-3Dtrafficonese&d=DwMFaQ&c=WvG0b4OO_RKn2Vh2-dPugA&r=Cfib0vLgl57EcKb5kqMLfkGUPwb3Ua04KZbqfr_IaFs&m=TDDSpWUiIrNTgLMjiCAngCNqiN1t4zmIHWvxj7NxuvY&s=kUK6s1Qi92xZcrxGMvDDwF_tpceCEEfGtz3iDziU4wA&e=>
>    - @troels
>    <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_r-2Ddbi_RPostgres_commits-3Fauthor-3Dtroels&d=DwMFaQ&c=WvG0b4OO_RKn2Vh2-dPugA&r=Cfib0vLgl57EcKb5kqMLfkGUPwb3Ua04KZbqfr_IaFs&m=TDDSpWUiIrNTgLMjiCAngCNqiN1t4zmIHWvxj7NxuvY&s=ew-Y7QiTuLPP7xYMLGODZkoTLhf9ZU2ZTJPtDcaRRkk&e=>
>    - @TSchiefer
>    <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_r-2Ddbi_RPostgres_commits-3Fauthor-3DTSchiefer&d=DwMFaQ&c=WvG0b4OO_RKn2Vh2-dPugA&r=Cfib0vLgl57EcKb5kqMLfkGUPwb3Ua04KZbqfr_IaFs&m=TDDSpWUiIrNTgLMjiCAngCNqiN1t4zmIHWvxj7NxuvY&s=pLhlfhm9HADT5jWmbZJOUxArbc3OulvxnYy-nJ5FT-g&e=>
>    - @zozlak
>    <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_r-2Ddbi_RPostgres_commits-3Fauthor-3Dzozlak&d=DwMFaQ&c=WvG0b4OO_RKn2Vh2-dPugA&r=Cfib0vLgl57EcKb5kqMLfkGUPwb3Ua04KZbqfr_IaFs&m=TDDSpWUiIrNTgLMjiCAngCNqiN1t4zmIHWvxj7NxuvY&s=LCaAx5ehEF5cQnG5xxTzYJXYNKPpcRWKolwIRw2v4w4&e=>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_r-2Ddbi_RPostgres_issues_312&d=DwMFaQ&c=WvG0b4OO_RKn2Vh2-dPugA&r=Cfib0vLgl57EcKb5kqMLfkGUPwb3Ua04KZbqfr_IaFs&m=TDDSpWUiIrNTgLMjiCAngCNqiN1t4zmIHWvxj7NxuvY&s=ICaO1EF_E7ZSp6RHR0_4gQtfU87vZSZIEQ_hwiEzN1Q&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AEGEAUVDCG7IC55X7NNBC5TTWNLNZANCNFSM475GO2FA&d=DwMFaQ&c=WvG0b4OO_RKn2Vh2-dPugA&r=Cfib0vLgl57EcKb5kqMLfkGUPwb3Ua04KZbqfr_IaFs&m=TDDSpWUiIrNTgLMjiCAngCNqiN1t4zmIHWvxj7NxuvY&s=52z_1Kh6lguOZz944fF3d3phs8rWtRXj5daR6azLpko&e=>
> .
>
-- 

Oz Raza
Data Platform Engineer | Stitch Fix
One Montgomery Tower Suite 1500
San Francisco, CA 94104

**Comment by Altons** [comment]
I agree

**Comment by etiennebr** [comment]
I agree

**Comment by baderstine** [comment]
I agree

**Comment by mmuurr** [comment]
I agree.

**Comment by thrasibule** [comment]
I agree

**Comment by imlijunda** [comment]
I agree

**Comment by baileych** [comment]
I agree

**Comment by zozlak** [comment]
I agree.

**Comment by trafficonese** [comment]
I agree

**Comment by TSchiefer** [comment]
I agree

**Comment by troels** [comment]
I agree

**Comment by lentinj** [comment]
I agree

**Comment by ateucher** [comment]
I agree

**Comment by krlmlr** [comment]
@JackStat @jaredk-porch: Are you ok with relicensing RPostgres under MIT?

**Comment by krlmlr** [comment]
@kofron: Did you use the @jaredk-porch handle when contributing to RPostgres? Are you ok with relicensing RPostgres under MIT?

**Comment by krlmlr** [comment]
Let's hope we can finalize this for the next version. Still missing confirmation/disapproval from @JackStat @jaredk-porch (@kofron?).

**Comment by hadley** [comment]
We have made a good-faith attempt to get consent from all contributor to the package under the previous license. This has included reviewing contributions to the package for non-trivial changes, seeking agreement to re-license with GitHub issues, sending a reminding after two weeks, and reaching out by e-mail (where possible).

Unfortunately, we have not received a response from @JackStat and @jaredk-porch. We have carefully reviewed their contributions. Given that the contributions are relatively small, and no one has objected to re-licensing across all tidyverse and r-lib repos, we are going to move ahead with the re-licensing. Of course, if we later discover that contributors are not happy with the re-licensing, we'll re-implement their changes.

**Comment by jakob-r** [comment]
I agree (although I feel my contribution should not count :) )

**Comment by galachad** [comment]
I agree.
