### ISSUE TITLE
"Key already exists"-Error, while ID is set to Identity "by default"

### ISSUE THREAD

**Issue by GitHubGeniusOverlord** [r-dbi/RPostgres#314]
Hi!
the postgresql documentation specifies, that an attribute of type "identity" which is set to
Identity "BY DEFAULT" can have its ID value overriden. In contrast Identity "ALWAYS" does not give precedence to a user specified value.

Using dbAppendTable() with RPostgres I dont get the expected behaviour: A column which has its identity set to "BY DEFAULT" keeps throwing the "Key already exists" error when submitting a user specified (duplicate) value as a key. Following the doc I expected it to accept the value.

I hope its a bug and not just me doing stuff wrong! ;) Thank You!

```r
#Run twice: 
dbAppendTable(con, name= "temp_202107", 
              value = data.table(
                    ID = 1 
              )
)
```

**Comment by krlmlr** [comment]
Works for me:

``` r
library(RPostgres)

con <- dbConnect(Postgres())

dbCreateTable(con, "test", data.frame(a = integer()), field.types = list(a = "int IDENTITY BY DEFAULT"))

dbAppendTable(con, "test", data.frame(a = 2))
#> [1] 1
dbAppendTable(con, "test", data.frame(a = 2))
#> [1] 1

dbReadTable(con, "test")
#>   a
#> 1 2
#> 2 2

dbRemoveTable(con, "test")


dbCreateTable(con, "test", data.frame(a = integer()), field.types = list(a = "int IDENTITY ALWAYS"))

dbAppendTable(con, "test", data.frame(a = 2))
#> [1] 1
dbAppendTable(con, "test", data.frame(a = 2))
#> [1] 1

dbReadTable(con, "test")
#>   a
#> 1 2
#> 2 2

dbRemoveTable(con, "test")
```

<sup>Created on 2021-08-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>
