### ISSUE TITLE
Installation on Centos8

### ISSUE THREAD

**Issue by beralef** [r-dbi/RPostgres#348]
An error occurred when I tried to install RPostgres package on Centos8 with postgresql-13 : 
-lpq -L/usr/lib64/R/lib -lR
/usr/bin/ld : ne peut trouver -lpq
collect2: error: ld a retourné le statut de sortie 1
make: *** [/usr/share/R/make/shlib.mk:10: RPostgres.so] Error 1
ERROR: compilation failed for package ‘RPostgres’

This error was due to default path and environment variables given by postgresql-13. The LIB_DIR wasn't set and the documentation of installation doesn't mention how to set it. I either didn't find any bug report for that problem. 

I correct that problem by modifying the configure shell to get the PKG_LIBS environment variable from the calling shell. 
But I guess that a cleaner solution consist to set the LIB_DIR environment variable (and export it) to the library installation directory (/usr/pgsql-13/lib/ by default). This solution would be reduced to a documentation mention. 

Hope this help

**Comment by krlmlr** [comment]
Thanks. Happy to review a pull request. Please keep in mind that the package must build on a variety of platforms and against different versions of libpq, I'm not sure how hard-coded paths help here.
