### ISSUE TITLE
Export connection_is_transacting

### ISSUE THREAD

**Issue by jakob-r** [r-dbi/RPostgres#349]
It would be very practical if `connection_is_transacting` was exported in some way. Unfortunately it is not part of any functionality defined in DBI but it could maybe included in dbGetInfo? 

If you agree I can open a PR

I want to avoid using unexported functions like that:

```r
RPostgres:::connection_is_transacting(db@ptr)
```

**Comment by krlmlr** [comment]
Thanks. Let's implement a `postgresIsTransacting()` function (doesn't have to be a method), we can think about including it in the DBI spec later.
