### ISSUE TITLE
Unable to create database connection, crashes, produces unprintable characters

### ISSUE THREAD

**Issue by geneorama** [r-dbi/RPostgres#398]
I'm getting an error when I try to connect with RPostgres. This is a fresh install of R / RStudio, but I was getting the same error a few weeks ago on a different machine.  I have no idea why the other machine started working. 

The error looks something like this: `Error in postgresqlNewConnection(drv, ...) : RS-DBI driver: (p?@ ;?);`, but sometimes the console refreshes before I can copy it out. 

It's difficult to provide a complete reproducible example, because you can't access this database. 

```r
CRED_DB <- yaml::read_yaml(pg_cred_file)
drv <- dbDriver("PostgreSQL")
con <- RPostgreSQL::dbConnect(drv, 
                              dbname = CRED_DB$database,
                              host = CRED_DB$host, 
                              port = CRED_DB$port,
                              user = CRED_DB$username, 
                              password = CRED_DB$password)
```

This is the result:
```r
>   con <- RPostgreSQL::dbConnect(drv, 
+                                 dbname = CRED_DB$database,
+                                 host = CRED_DB$host, 
+                                 port = CRED_DB$port,
+                                 user = CRED_DB$username, 
+                                 password = CRED_DB$password)
o��) in postgresqlNewConnection(drv, ...) : RS-DBI driver: (�
```

These errors are all in Windows (10 and 11)

**Comment by krlmlr** [comment]
Thanks. What happens when you use the RPostgres package?

**Comment by geneorama** [comment]
What do you mean? I'm trying to use it but the connection is failing. 

By the way, this is a faster route toward reproduction of the error:
![image](https://user-images.githubusercontent.com/1392068/176794490-3818b8fc-8107-4cdf-a9f0-497655b4424b.png)

**Comment by krlmlr** [comment]
It looks like you're using the RPostgreSQL package, which is different.

**Comment by geneorama** [comment]
Well, that's embarrassing. However, I do get a similar error with RPostgres. 

I restarted the project after installing RPostgres to make sure that no other dependencies or packages were loaded.

![image](https://user-images.githubusercontent.com/1392068/177623636-73adc627-b809-4bcd-b482-ce65cc978a77.png)

**Comment by geneorama** [comment]
That takes care of that. I apologize for wasting your energy. 

I will let the devs at `RPostgresSQL` know though.

**Comment by krlmlr** [comment]
Thanks, please let me know where documentation can be improved.

I have had trouble reaching RPostgreSQL maintainers in the past.
