### ISSUE TITLE
Converting RPostgres backend to cpp11

### ISSUE THREAD

**Issue by pachadotdev** [r-dbi/RPostgres#400]
Hi!

I wonder if there's interest in doing this. The reason to do this is that the legal department where I'm working prefers Apache to MIT, and MIT over any other license. This is because of many different implications I don't understand so well, including places where software is a "thing" like a car or similar.

**Comment by pachadotdev** [comment]
there's a big progress here https://github.com/r-dbi/RPostgres/pull/419
and some minor adjustments here https://github.com/Antonov548/RPostgres/pull/1

**Comment by pachadotdev** [comment]
also @krlmlr, any option to relicense as MIT/Apache same as RMariaDB?

**Comment by krlmlr** [comment]
Done now.

**Comment by pachadotdev** [comment]
> Done now.

amazing! my help here was minimal, but glad to have avoided you 1-2 headaches with the bashims
