### ISSUE TITLE
Printing of "invalid" `PqConnection` object

### ISSUE THREAD

**Issue by nbenn** [r-dbi/RPostgres#403]
For unit testing purposes, I'm trying to create a dummy `PqConnection` object. One minor inconvenience is that while `format.PqConnection()` checks for validity and handles the "invalid" case gracefully, `show_PqConnection()` does not. 

---

Therefore printing an object created as `new("PqConnection")` will trigger an error:

```r
library(RPostgres)
dummy <- new("PqConnection")
format(dummy)
#> [1] "<PqConnection> DISCONNECTED"
dummy
#> Error: Invalid connection
```

Is there a reason for not calling `format()` internally in `show_PqConnection()`? Happy to submit a PR if you're open to the idea.

**Comment by krlmlr** [comment]
How does dbplyr solve this?

**Comment by krlmlr** [comment]
Connection objects should be created with `dbConnect()` only, creation via `new()` is currently not supported.
