### ISSUE TITLE
Connection closed unexpectedly by server

### ISSUE THREAD

**Issue by aliarsalankazmi** [r-dbi/RPostgres#406]
*Apologies in advance for not having a reprex, due to working in a sensitive environment*.

I was using the following code to connect to a database. It works perfectly for one environment (UAT) but fails in another (production).

```
con <- DBI::dbConnect(RPostgres::Postgres(), dbname = "my_db", host = "10.10.10.194", port = 5432, user = "my_user", password = "my_password")
# OR
con <- DBI::dbConnect(RPostgres::Postgres(), dbname = "my_db", hostaddr = "10.10.10.194", port = 5432, user = "my_user", password = "my_password")


Error: server closed the connection unexpectedly. This probably means the server terminated abnormally before or while processing the request.
```

- I am able to `telnet` to the host address + port
- IT is not storing logs, so apparently nothing that I can check from the server side
- I am hitting the wall with this, so really appreciate any pointers on how to debug

![image](https://user-images.githubusercontent.com/5294000/193845769-20509b63-95ed-4784-911f-afd08da20581.png)

**Comment by aliarsalankazmi** [comment]
Finding my feet by debugging as much as I can/looking up more ways to debug S4.
A call to `traceback` shows this:

![image](https://user-images.githubusercontent.com/5294000/193850166-7e89df39-1ec0-4f23-8a05-6377487ebe78.png)

**Comment by aliarsalankazmi** [comment]
After checking with the database admin and IT, I am being advised this might be due to proxy being utilised under the wraps by dbConnect (?)

Trying to debug now to see if this is the case (debugging is more complicated because simply using `debug` is not very helpful)...

**Comment by krlmlr** [comment]
Thanks. Can you connect with another client, e.g., the `psql` command line or a GUI?

**Comment by aliarsalankazmi** [comment]
Thanks a lot for the message, @krlmlr!

I tried `telnet` if that counts. I don't have others like PgAdmin just yet, but I will ask for them to be installed so I can check.
Could you also suggest how I can see under the wraps of the dbConnect method? I tried `traceback` but surely there will be better ways?

**Comment by aliarsalankazmi** [comment]
@krlmlr , I could not check via a GUI, but I just checked with python using `psycopg2`.
It threw the same error (perhaps unsurprisingly as it too is based on `libpq`)

**Comment by krlmlr** [comment]
Thanks. I've seen cases where `psql` et al. works but RPostgres doesn't. Unfortunately, if both don't work, I have to ask you to troubleshoot `psql` or PgAdmin first.

**Comment by aliarsalankazmi** [comment]
Thanks @krlmlr

I and my IT have not been able to diagnose this issue yet.
Hopefully in the next couple of days IT will have installed a client like PgAdmin or psql for me to check. If not, then I will close this issue.

Many thanks for the patience, BTW!

**Comment by aliarsalankazmi** [comment]
Turns out the network team had assigned an incorrect security policy to my account due to which I was unable to connect.

Apologies for the hassle!

**Comment by krlmlr** [comment]
Thanks for the heads-up! Glad it works now for you.
