### ISSUE TITLE
Cannot use DBI::dbWriteTable to save temporary table to Redshift

### ISSUE THREAD

**Issue by gui-salome** [r-dbi/RPostgres#410]
When trying to write a simple temporary table to Redshift, I run into an error.

```r
connection <- DBI::dbConnect(drv = RPostgres::Postgres(), 
                             host = host, 
                             port = port, 
                             dbname = dbname, 
                             user = user, 
                             password = password)
DBI::dbWriteTable(conn = connection, name = "iris", value = iris)
```
<img width="746" alt="Screenshot 2022-11-04 at 9 27 44 AM" src="https://user-images.githubusercontent.com/68299186/199983782-36bcec12-7cc8-4531-8abe-e94db3c15836.png">

Any idea what could be causing this issue? A similar code (substituting `name` by `DBI::Id(schema, table)`) works fine for writing permanent tables.

**Comment by krlmlr** [comment]
Thanks. Can you try `RPostgres::Redshift()` instead of `RPostgres::Postgres()` ?

**Comment by gui-salome** [comment]
It works using `Redshift` instead of `Postgres`. Thanks for helping @krlmlr.
