### ISSUE TITLE
Redshift varchar character length not respected by dplyr::rows_*()

### ISSUE THREAD

**Issue by samterfa** [r-dbi/RPostgres#412]
I first created [this issue in the dbplyr repo](https://github.com/tidyverse/dbplyr/issues/1050) but their suggestion is that it's an RPosgres issue.

I hope this is the right place for this issue. I know that dplyr::rows_*() are experimental.

When writing a text value to a Redshift table whose column is varchar(anything larger than 256), using dplyr::rows_append() or dplyr::rows_update() seems to cast the text to varchar(256) before writing to the database. Longer texts will then fail to write even though the table should be able to accommodate them.

To reproduce the issue:
- Create a Redshift table with columns id and txt (I haven't run into this with Postgres connections but it might happen there too).
- Make the datatype of the txt column varchar(max, or anything larger than 256)
- Connect to the table using a privileged user. I use RPostgres::Redshift() (but this isn't the issue).
- This will work successfully.
```r
dplyr::rows_append(x = dplyr::tbl(src = redshift_conn, DBI::Id(schema = schema, table = table)), y = tibble(id = 1, txt = paste(rep('a', 256), collapse = '')), copy = TRUE, in_place = TRUE)
```
- This will fail with `Error: Failed to fetch row: ERROR:  value too long for type character varying(256).`
```r
dplyr::rows_append(x = dplyr::tbl(src = redshift_conn, DBI::Id(schema = schema, table = table)), y = tibble(id = 2, txt = paste(rep('a', 257), collapse = '')), copy = TRUE, in_place = TRUE)
```
- But using RPostgres::dbAppendTable() works with the same data that failed with dplyr::rows_append().
```r
RPostgres::dbAppendTable(conn = redshift_conn, name = DBI::Id(schema = schema, table = table), value = tibble(id = 2, txt = paste(rep('a', 257), collapse = '')), row.names = NULL)
```

Somewhere along the line the text value is cast from varchar(65535) to varchar(256) for rows_append() and rows_update(), and I haven't figured out where.

Thanks!

**Comment by krlmlr** [comment]
Thanks. Can you use `dbAppendTable()` or the like to create a temporary table on the database, and then use `rows_append(copy = FALSE)` to copy to the persistent table?

In the dbplyr issue, I see that `dbWriteTable()` has the same problem as `rows_append()` . Can you please provide more detail in how `dbWriteTable()` compares to `dbAppendTable()` ? What happens if the table is created with `dbCreateTable()` and then data is appended with `dbAppendTable()` ?

What does `dbDataType()` return for your data?

**Comment by samterfa** [comment]
`dbAppendTable()` actually works fine already for appending data to a Redshift table with the appropriate datatype. This is why I thought the issue might be a dplyr or dbplyr issue instead. `dplyr::rows_append()` is broken for me and should work, but it's not my main concern at the moment since I can use the `dbAppendTable()` workaround. 

What I'm really after is `dplyr::rows_update()` which is a really simple way to update rows of a database. I haven't found a good workaround for this. I am having trouble tracing what `dplyr::rows_update()` is doing and how the ecosystem of RPostgres, dbplyr, and dplyr work together.

**Comment by krlmlr** [comment]
Thanks. I'm typically using separate steps for bringing data into the database and updating a live data model:

1. Copy data as temporary table
2. Use `rows_xxx(copy = FALSE)`  (the default)

This is a bit more tedious, but gives the best control.

**Comment by krlmlr** [comment]
Realizing I didn't really answer your `rows_update()` question.

`rows_update()` and the other `rows_*()` functions work best if the data is already in the database, e.g., in a temporary table. Then you can use `update = FALSE` to avoid copying, this simplifies the procedure. You prepare a table that contains the keys and new values you want to update, copy it to the database, and call `rows_update()` . Does that help?

**Comment by samterfa** [comment]
We have moved to BigQuery so I am closing the issue. Thanks for all your help!
