### ISSUE TITLE
collation warning on Ubuntu 22.04

### ISSUE THREAD

**Issue by pachadotdev** [r-dbi/RPostgres#415]
After updating to Ubuntu 22.04 all connections show this warning.

```
WARNING:  database "test" has a collation version mismatch
DETAIL:  The database was created using collation version 2.31, but the operating system provides version 2.35.
HINT:  Rebuild all objects affected by collation in this database and run ALTER DATABASE test REFRESH COLLATION VERSION, or build PostgreSQL with the right library version.
```

Probably we can detect this message with a regex and suggest the user to rebuild indexes with a more informative message like this:

_Based on https://techcommunity.microsoft.com/t5/azure-database-for-postgresql/don-t-let-collation-versions-corrupt-your-postgresql-indexes/ba-p/1978394 you should run 
REINDEX DATABASE test;
ALTER database test REFRESH COLLATION version;_

**Comment by krlmlr** [comment]
Thanks. What do the warnings look when run from an R connection? If it's clear enough what to do, users should be able to handle that.

**Comment by pachadotdev** [comment]
> Thanks. What do the warnings look when run from an R connection? If it's clear enough what to do, users should be able to handle that.

sorry  the delay @krlmlr 
the message in the backticks is exactly what I get from R, it is not informative as it should say "rebuild indexes"

I'll send a PR

**Comment by krlmlr** [comment]
It says "Rebuild all objects affected by collation", and search engines will find this issue, I hope. Perhaps you could take this to Postgres, so that the error message is made a bit clearer there?

**Comment by krlmlr** [comment]
I don't think we should use regexes on error messages.
