### ISSUE TITLE
relicense RPostgres as MIT

### ISSUE THREAD

**Issue by pachadotdev** [r-dbi/RPostgres#420]
Briefly mentioned here https://github.com/r-dbi/RPostgres/issues/400. There is a detailed explanation about the relevance of this at https://github.com/r-lib/usethis/issues/1253.

**Comment by krlmlr** [comment]
This isn't straightforward because we have GPL licensed code here that we'd need to rewrite.

**Comment by dpprdan** [comment]
duplicates #312
