### ISSUE TITLE
Bigints in dbQuoteLiteral

### ISSUE THREAD

**Issue by karawoo** [r-dbi/RPostgres#435]
I noticed that `dbQuoteLiteral()` casts integer64 values as floats:
``` r
library("DBI")
conn <- dbConnect(RPostgres::Postgres())

(x <- bit64::as.integer64(1))
#> integer64
#> [1] 1
dbQuoteLiteral(conn, x)
#> <SQL> 1::float8
```
I'd expect `<SQL> 1::int8` instead. Would you consider a PR to support bigints here?

**Comment by krlmlr** [comment]
Thanks. If we support this in `dbDataType()`, we should also make sure to support it with `dbBind()` and perhaps `dbWriteTable()` . I wonder how much work that would be.

**Comment by karawoo** [comment]
I believe it is already supported in those places as of v1.1.0 https://github.com/r-dbi/RPostgres/blob/main/NEWS.md#rpostgres-110-2018-04-04

> Values of class "integer64" are now supported for dbWriteTable() and dbBind() (#178).

**Comment by krlmlr** [comment]
Thanks, good catch. I agree that we should definitely fix `dbDataType()` .
