### ISSUE TITLE
Warning with untyped NULL

### ISSUE THREAD

**Issue by krlmlr** [r-dbi/RPostgres#50]
`SELECT NULL as a` leads to the following warning:

In result_create(conn@ptr, statement) :
  Unknown field type (705) in column a

Related: #30

Test name: "data_null".

**Comment by krlmlr** [comment]
The same error occurs when selecting string constants.

**Comment by krlmlr** [comment]
Types are defined here: http://doxygen.postgresql.org/include_2catalog_2pg__type_8h_source.html

Should be used in PqResult.h instead of hard-coded numbers. Also think about mapping of NULL (2278, 705).

**Comment by hadley** [comment]
Hard coded numbers are easier because the type catalog changes with each version.
