### ISSUE TITLE
Data type for timestamps

### ISSUE THREAD

**Issue by krlmlr** [r-dbi/RPostgres#53]
should be POSIXct.

Test name: "data_timestamp".

**Comment by krlmlr** [comment]
Probable reason:

```
> DBI::dbDataType(RPostgres::Postgres(), Sys.Date())
[1] "REAL"
```

**Comment by JackStat** [comment]
Is this an issue that should be fixed in `DBI` or `RPostgres`?

**Comment by krlmlr** [comment]
RPostgres, see https://github.com/rstats-db/RPostgres/blob/2a8bf99bdd6d1e539e69643adc947e9c89ba54fc/R/connection.R#L92-L94

**Comment by tkschmidt** [comment]
In postgresqlExecStatement(conn, statement, ...) :
  RS-DBI driver warning: (unrecognized PostgreSQL field type abstime (id:702) in column 2) 

Runnning postgres server version 8.4, RPostgres seems to be the newest version.

**Comment by RoyalTS** [comment]
What would it take to get this fixed? I assume just adding `POSIXct = "DATETIME"` to that list wouldn't do it?
