### ISSUE TITLE
documentation on select with bind parameters?

### ISSUE THREAD

**Issue by dckc** [r-dbi/RPostgres#72]
The README here claims "full support" but I can't find any documentation. Help?

Perhaps it should be part of the DBI documentation, but I just see it in "Open Issues and Limitations" in https://github.com/rstats-db/DBI/blob/master/vignettes/DBI-1.Rmd

**Comment by krlmlr** [comment]
The documentation is currently a bit lacking. A simple example (using RSQLite):

```
con <- dbConnect(RSQLite::SQLite())
res <- dbSendQuery(con, "SELECT ? AS a")
dbBind(res, list(1))
dbFetch(res)
##   a
## 1 1
dbClearResult(res)
dbDisconnect(con)
```

You need to use `$1`, `$2`, instead of `?` for RPostgres.

**Comment by dckc** [comment]
I somehow found the `$1` clue ... maybe from Postgres docs or something. Please do document that with this package.

I ended up with this little utility function:

```{r}
makePreparedQuery <- function(conn) {
  function(statement, ...) {
    params = list(...)

    rs <- dbSendQuery(conn, statement)
    on.exit(dbClearResult(rs))
    
    if (length(params) > 0) {
      dbBind(rs, params)
      }
    
    df <- dbFetch(rs, n = -1, ...)
    if (!dbHasCompleted(rs)) {
      warning("Pending rows", call. = FALSE)
      }
    
    df
    }
  }
```

for example:

```{r}
cdwq <- makePreparedQuery(cdw)
cdwq("select 2 + 2")
cdwq("select $1 + 5", p1=3)
```

**Comment by parisni** [comment]
hello dckc,
The example you provide does not work with the actual version.
Do somebody knows how make prepared queries work ?
Thanks by advance,

**Comment by krlmlr** [comment]
@parisni: Here's the `RPostgres` version:

```
con <- dbConnect(RPostgres::Postgres())
res <- dbSendQuery(con, "SELECT ($1::numeric) AS a")
dbBind(res, list(1))
dbFetch(res)
```

Does that work for you?

**Comment by parisni** [comment]
Right the cast makes it working. Thanks, I hope the documentation will be updated soon about that.

**Comment by krlmlr** [comment]
`dbBind()` documentation has been updated and now includes a reference to `$1`. Please open a new issue for further documentation problems.
