### ISSUE TITLE
parameter query

### ISSUE THREAD

**Issue by lsusatyo-gcmlp** [r-dbi/RPostgres#84]
Hi,

I'm just wondering if the parameter support for dbSendQuery has been implemented. I don't think it's there yet, am I right?

find_student <- function(db, name) {
 sql <- "SELECT \* FROM Students WHERE (name = ?);
 dbGetQuery(db, sql, list(name))
}
find_student("Hadley")

**Comment by krlmlr** [comment]
There's dbBind(), which should work already. The interface might change soon, though -- especially the syntax of the placeholders (currently $1, $2, ... as far as I remember).

**Comment by renrutnosaj** [comment]
I'm using it semi-successfully. Having trouble sending NULL as a parameter, eg:

In PostgreSQL:

`create table foo (ival int, tval text, bval bytea);`

In R:

This works:

`res <- dbSendQuery(con, "INSERT INTO foo VALUES($1, $2, $3)",  params=list(ival=1, tval= 'not quite null', bval=charToRaw('asdf')))`

But this throws an error (r-side, I suspect based on the error message's brevity):

`res <- dbSendQuery(con, "INSERT INTO foo VALUES($1, $2, $3)", params=list(ival=NULL, tval= 'not quite null', bval=charToRaw('asdf')))`

Error: expecting a string

Substituting NA would be fine with me, but it isn't a work-around - a literal 'NA' gets written to the database. 

Using e.g. integer(0) gives the same "expecting a string" message.

R version 3.3.1, RPostgres version 0.1-2, PostgreSQL version 9.5.

**Comment by krlmlr** [comment]
`NULL` parameters are also discussed in #95, is this the same problem?
