### ISSUE TITLE
Request to have "dbUpsertTable" 

### ISSUE THREAD

**Issue by arturosaco** [r-dbi/RPostgres#87]
It'd be nice to have a function that performed upserts on multiple rows of a database table in the spirit of dbWriteTable. This functionality was introduced in Postgres 9.5. 

At the moment I've come up with an R written wrapper to perform such upserts in a single row but the performance is much too slow, specially when iterating through many rows.

```
upsert.wrapper <- function(con.x, target_table, 
    unique_constraints, update_vars, new_values){
    names.aux <- names(new_values)
    new_values <- as.character(new_values)
    new_values[new_values == "NA"] <- NA

    q.string <- paste0(
        "INSERT INTO ", target_table, 
        "(", paste0(names.aux, collapse = ","),") VALUES (", 
        new_values %>% 
            dbQuoteString(DBI::ANSI(), .) %>%
            paste0(collapse = ", "), 
        ") ON CONFLICT (", paste(unique_constraints, collapse = ", "),")
        DO UPDATE SET ",
        paste0(update_vars, " = ", "EXCLUDED.", update_vars, collapse = ", ")
    )

    db.q <- dbSendQuery(con.x, q.string)
    out <- dbGetRowsAffected(db.q)
    invisible(dbClearResult(db.q))
}
```

I wonder if there are plans to add this functionality using lower level C++ code, as I suspect this would enhance performance a lot. 

I'd be happy to contribute to this end if you think it's viable. If you do I'd greatly appreciate some pointers on how to get started on this.

**Comment by krlmlr** [comment]
Related: https://github.com/rstats-db/RMySQL/issues/68.

I'm a bit unsure where this should live. This looks like it's a bit too specific for DBI, and the functionality is likely to vary between DBMS.

Perhaps it would be great to have this in a separate package, with implementations for RPostgres, RMySQL and RSQLite (see http://stackoverflow.com/q/418898/946850). Based on that, we could evaluate if and how it's included in DBI.

**Comment by krlmlr** [comment]
Didn't mean to close it.

**Comment by ankane** [comment]
Hey @arturosaco and @krlmlr, I created a package named [dbx](https://github.com/ankane/dbx) for this (supports upserts for Postgres, MySQL, and SQLite).

**Comment by arturosaco** [comment]
Niiiicee!! I'll let you know if I have any feedback!

**Comment by datawranglerai** [comment]
@ankane the dbx package is exactly what I've been searching for, thank you!

**Comment by krlmlr** [comment]
Thanks @ankane for working on _dbx_! This fills a gap which I think _DBI_ can't cover.
