### ISSUE TITLE
dbColumnInfo doesn't match DBI spec

### ISSUE THREAD

**Issue by natecobb** [r-dbi/RPostgres#92]
I'm trying to port some code over that uses the RPostgreSQL driver; I need to be able check the actual SQL/Postgres variable type. The DBI man page for dbColumnInfo states "Methods MUST include name, field.type (the SQL type), and data.type (the R data type) columns"

RPostgres currently returns just "name" and "type" which matches "data.type" (i.e., the R data type). Any chance to move towards DBI and compatibility with RPostgreSQL? 

For what its worth RPostgreSQL also uses the column name "type" but uses it for "field.type" so they will collide while RMySQL has the same behavior leaving RPostgres as the outlier.

**Comment by krlmlr** [comment]
Thanks, we should definitely be consistent here.

**Comment by natecobb** [comment]
My suggestion would be return the DBI standard columns, but also return the non-standard "type" with "field.type" in it to match the other drivers

**Comment by krlmlr** [comment]
Thanks, noted. Reopening to make sure we don't forget.

**Comment by krlmlr** [comment]
`dbColumnInfo()` now expects `"name"` and `"type"` columns: https://dbi.r-dbi.org/reference/dbcolumninfo.

**Comment by ankane** [comment]
Hey @krlmlr, what's the best place to discuss adding the native database type to the `dbColumnInfo` spec? I think that's more useful than the R type (which can be determined by creating an empty data frame as shown in the link you posted).
