### ISSUE TITLE
Parameterized queries not working with NULL values

### ISSUE THREAD

**Issue by renrutnosaj** [r-dbi/RPostgres#95]
# Summary

NULL and zero-length vectors (e.g. character(0) ) cause an error when used as parameters in a parameterized query. 
# Expected Behaviour

I haven't found RPostgres documentation that states explicitly what an R NULL should produce on the query end, but a database NULL seems reasonable. If this is too difficult, some other way telling the database to use NULL as a query parameter would be very beneficial.
# Actual Behaviour

Here's a toy example:

In PostgreSQL:

```
create table foo (ival int, tval text, bval bytea);
```

In R:

This works:

```
res <- dbSendQuery(con, "INSERT INTO foo VALUES($1, $2, $3)", 
                   params=list(ival=1, 
                               tval= 'not quite null',
                               bval=charToRaw('asdf')
                               )
                    )
```

But this throws an error:

```
res <- dbSendQuery(con, "INSERT INTO foo VALUES($1, $2, $3)",
                   params=list(ival=NULL, 
                               tval= 'not quite null',
                               bval=charToRaw('asdf')
                               )
                   )
```

Using RPostgres, the error message is:

> Error: expecting a string

The error message is the same with NULL for tval or bval.

Thanks for your attention on this matter.

Regards

Jason

**Comment by krlmlr** [comment]
You need to use `ival = NA` instead of `ival = NULL`. (`NA` are mapped to SQL `NULL`, and vice versa.)
